TASEmulators/BizHawk

BizHawk.Client.EmuHawk/tools/Lua/LuaConsole.Designer.cs, BizHawk.Client.EmuHawk/tools/Lua/LuaConsole.resx
With the split container, resizing the window will properly reformat the output section as well as allow users to resize it.
=> Add a split container to LUA console window.

output/gamedb/gamedb_n64.txt
This game makes heavy use of framebuffer effects for the pause menu and zipper transitions, enable them by default.
"Alternate Texture Size Method" causes issues with water textures, disable it by default.
=> Fix per game settings for DK64 + Glide64mk2

BizHawk.Emulation.Cores/Consoles/Nintendo/N64/NativeAPI/mupen64plusCoreApi.cs
Multiple handles to the core config section were being opened in some cases, this commit squishes the extra calls to m64pConfigOpenSection
=> Clean up code that applies N64 core settings

BizHawk.Common/Extensions/StringExtensions.cs
This fixes an exception when pressing "Ok" on the "Go to Address" input prompt in the Hex Editor with an empty string
=> Better null checks in string validation functions

BizHawk.Emulation.Cores/Computers/Commodore64/C64.Input.cs, BizHawk.Emulation.Cores/Computers/Commodore64/C64.Motherboard.cs, BizHawk.Emulation.Cores/Computers/Commodore64/C64.MotherboardInterface.cs, BizHawk.Emulation.Cores/Computers/Commodore64/Cartridge/CartridgeDevice.cs, BizHawk.Emulation.Cores/Computers/Commodore64/Cartridge/Mapper0000.cs, BizHawk.Emulation.Cores/Computers/Commodore64/Cartridge/Mapper0005.cs, BizHawk.Emulation.Cores/Computers/Commodore64/Cartridge/Mapper000B.cs, BizHawk.Emulation.Cores/Computers/Commodore64/Cartridge/Mapper000F.cs, BizHawk.Emulation.Cores/Computers/Commodore64/Cartridge/Mapper0012.cs, BizHawk.Emulation.Cores/Computers/Commodore64/Cartridge/Mapper0013.cs, BizHawk.Emulation.Cores/Computers/Commodore64/Cartridge/Mapper0020.cs, BizHawk.Emulation.Cores/Computers/Commodore64/Cassette/CassettePort.cs, BizHawk.Emulation.Cores/Computers/Commodore64/Cassette/CassettePortDevice.cs, BizHawk.Emulation.Cores/Computers/Commodore64/Cassette/TapeDrive.cs, BizHawk.Emulation.Cores/Computers/Commodore64/MOS/Chip6526.cs, BizHawk.Emulation.Cores/Computers/Commodore64/MOS/Cia.Port.cs, BizHawk.Emulation.Cores/Computers/Commodore64/MOS/Cia.cs, BizHawk.Emulation.Cores/Computers/Commodore64/Media/Disk.cs, BizHawk.Emulation.Cores/Computers/Commodore64/Media/Tape.cs, BizHawk.Emulation.Cores/Computers/Commodore64/SaveState.cs, BizHawk.Emulation.Cores/Computers/Commodore64/Serial/Drive1541.FluxTransitions.cs, BizHawk.Emulation.Cores/Computers/Commodore64/Serial/Drive1541.IDisassemblable.cs, BizHawk.Emulation.Cores/Computers/Commodore64/Serial/Drive1541.cs, BizHawk.Emulation.Cores/Computers/Commodore64/Serial/SerialPort.cs, BizHawk.Emulation.Cores/Computers/Commodore64/Serial/SerialPortDevice.cs
When saving data from modified cartridge flash (EasyFlash) or on disk (D64, G64), savestates will now have a delta of the modified data rather than an image of the original data, preventing from distributing the original media in savestates.
=> C64 delta savestates

BizHawk.Client.EmuHawk/BizHawk.Client.EmuHawk.csproj, BizHawk.Client.EmuHawk/FileLoader.cs, BizHawk.Client.EmuHawk/MainForm.Events.cs
Allows dragging-and-dropping of multiple files onto a running BizHawk window.
Currently, dragging-and-dropping multiple files of the same classification is disabled.  Classifications are listed in the LoadOrdering Enum, and include the order in which those types of files should be loaded (no state before ROM, etc.)  The current ordering is ROM, state, watch, CDL file, Lua session, Lua script, cheat file, [movie file and legacy movie file].
The next thing to do is allow dropping archives and extracting the relevant files from it, but the current hurdle is that any such loaded file would have to be read-only, as re-saving into the archive could be problematic.  Furthermore, all of the existing functions (copied and split into the Loaders region) accept filenames and not streams, which means …
=> Expanded drag and drop

BizHawk.Emulation.Cores/Consoles/Atari/2600/Atari2600.Core.cs, BizHawk.Emulation.Cores/Consoles/Atari/2600/Tia/TIA.cs
Now samples sound at exact explicit times each scanline.
Much simpler, but still sounds the same as before (i.e. some sounds are still wrong.)
Next Step: fix TIA.Audio
=> Rewrite A2600 Audio

BizHawk.Emulation.Cores/Consoles/Atari/2600/Tia/Tia.Audio.cs
finally found this bug, fixes several games where sounds were higher pitch then supposed to be (notably Combat)
=> Fixed high pitch bug

BizHawk.Emulation.Cores/CPUs/MOS 6502X/Execute.cs, BizHawk.Emulation.Cores/Consoles/Nintendo/NES/PPU.cs, BizHawk.Emulation.Cores/Consoles/Nintendo/NES/PPU.regs.cs, BizHawk.Emulation.Cores/Consoles/Nintendo/NES/PPU.run.cs
6502: Update behaviour of some undocumented opcodes. Now passes instr_misc/instr_misc. I couldn't find anything else to test it against.
NesHawk: Fixes 4014 read behavior. Fixes sprite evaluation. Combination of these things fixes Micro Machines, and also passes:
sprite_overflow_tests/3.Timing
sprite_overflow_tests/4.Obscure
Feedback welcome! 
I did a lot of testing and didn't find any bugs, but maybe someone will spot something.
=> NesHawk and 6502 bug Fixes

BizHawk.Emulation.Cores/Consoles/Nintendo/NES/APU.cs, BizHawk.Emulation.Cores/Consoles/Nintendo/NES/NES.Core.cs, BizHawk.Emulation.Cores/Consoles/Nintendo/NES/NES.IStatable.cs
passes: sprdma_and_dmc_dma
I am very confident the implementation is correct and cycle accurate, it also matches results from visual 2A03
fails: 4_dma_and_irq
This test passed previously due to a timing bug. Frame IRQ is the next big thing to work on
=> Inital DMA commits

BizHawk.Emulation.Cores/Consoles/Nintendo/SNES/LibsnesCore.cs
Fixed the bug where if a tracelog line contains more than one "[", everything after the second [ will be mistakenly thrown out.
=> Fix SNES trace logging to not lose information

BizHawk.Client.EmuHawk/tools/TraceLogger.cs
- Prevents an unhandled exception when saving a log from the window
(opposed to file)
=> Fix File->Save Log menu item in Trace Logger window

BizHawk.Client.EmuHawk/MainForm.cs
Changes the FPS counter to be smoother.
Why: FPS counter has a bug where it doesn't normalize the frame count to
the time passed since last update. This can result in an error of 1 FPS.
When running at 30 FPS, that is ~3.33%. The lower the FPS, the worse
this error grows.
1) Adds a parameter for how often to update the FPS (e.g. 16 times per
second).
2) Normalizes to the number of seconds passed since last update (fixing
the bug).
3) Adds a smoothing parameter (e.g. weigh the most recent interval at
8x, and normalize with current displayed data). This results in less
jumpy FPS because it takes into account historical data.
=> Create Smoother FPS Counter

BizHawk.Client.EmuHawk/MainForm.cs
1) Refactors volume calculations to be easier to follow by putting them near eachother.
2) Fixes Mute Frame Advance setting. Previously it didn't do anything. Now when you hold "F", it will mute as expected.
_[removed, but easy to add back in] 3) Allow Fast Forward Volume setting to be louder than Normal Volume. Previously it multiplied by the Normal Volume setting, which could only make it quieter._
=> Fix Volume Controls

BizHawk.Client.MultiHawk/Mainform.cs
I noticed an unreachable code warning when compiling, so I investigated.
This corrects a merge error from 0b4fc8b6a540ed43bdfde24bcc09f5cebf64f3ff that was incorrectly fixed in 20fb060c65bb7973862b399f8dc59ad28019c540.
Specifically, all code after the `NES.BootGodDB.GetDatabaseBytes` delegate creation was put inside the delegate instead of remaining after it. This made it unreachable and never execute, which in turn made it impossible to actually run MultiHawk.
This has been broken for over three months, which makes me wonder if anyone actually uses MultiHawk?
=> MultiHawk: Make unreachable code in Mainform ctor reachable again.

BizHawk.Client.EmuHawk/tools/Lua/Libraries/EmuLuaLibrary.Gui.cs
Like I mentioned on the BizHawk section of the TASVideos forums (http://tasvideos.org/forum/viewtopic.php?p=450935#450935 ), I decided to add alignment options to gui.DrawText(). Compared to that post, I swapped "top" and "bottom" to be consistent with how I did "left" and "right".
This is both my first time contributing to an open-source project and my first time coding in C#, so it may be a bit rough -- so let me know if anything needs to be cleaned up or changed. ^^;
=> Added horizalign and vertalign to DrawText

BizHawk.Client.EmuHawk/tools/Lua/LuaCanvas.cs
Brings canvas up to feature parity with EmuLuaLibrary.Gui.
The features added here are slightly altered versions of those already in EmuLuaLibrary.Gui. The only difference in behavior should be that when a file is not found using DrawImage or DrawIcon no error message is printed.
=> LuaCanvas: Add drawing features

BizHawk.Client.EmuHawk/MainForm.cs
Two new command line parameters were added:
```
--lua=
--luaconsole
```
The first one opens a console and loads the specified script.
The second one just opens the Lua console.
=> Added support for Lua scripts via the command line

BizHawk.Client.Common/PathManager.cs, BizHawk.Client.Common/config/Config.cs, BizHawk.Client.EmuHawk/MainForm.Designer.cs, BizHawk.Client.EmuHawk/MainForm.Events.cs, BizHawk.Client.EmuHawk/MainForm.cs, BizHawk.Client.EmuHawk/config/GuiOptions.Designer.cs, BizHawk.Client.EmuHawk/config/GuiOptions.cs
Following on the menu item and hotkey to save SaveRAM, I created a menu to choose how often you want your save to be saved during play.  Manually flushing SaveRAM resets the counter, automatic saving in the core frame loop is done after the movie is handled that frame.
Fun fact: a 1 frame flush timer is workable on a RAM disk, depending on the speed of various computer subsystems.  Writing 60 files per second to flash (SSD, SD, etc) lags the SNES core a little bit, and could be mildly abusive of the storage hardware.  Trying it on a hard drive was not fun.
=> Timed SaveRAM flush to disk

BizHawk.Emulation.Cores/BizHawk.Emulation.Cores.csproj, BizHawk.Emulation.Cores/Consoles/Nintendo/Gameboy/Gambatte.ILinkable.cs, BizHawk.Emulation.Cores/Consoles/Nintendo/Gameboy/Gambatte.cs
Might as well use ```ILinkable``` for the little status icon, didn't even realize it was a thing when making #982 since its only used one other time in BizHawk (in ```GambatteLink```)
=> Make Gambatte show link status for printer connection

Assets/defctrl.json, BizHawk.Client.EmuHawk/MainForm.Designer.cs, BizHawk.Client.EmuHawk/MainForm.Events.cs, BizHawk.Emulation.Cores/Consoles/Sega/SMS/SMS.IEmulator.cs, BizHawk.Emulation.Cores/Consoles/Sega/SMS/SMS.ISettable.cs, BizHawk.Emulation.Cores/Consoles/Sega/SMS/SMS.IStatable.cs, BizHawk.Emulation.Cores/Consoles/Sega/SMS/SMS.Input.cs
To switch controllers, go to _SMS_ -> _Controller Type_ -> _Paddle_.
Uses left analog stick on a game pad, by default; can be remapped of course.
I would not recommend the alternative digital left/right inputs, although they are technically usable in Alex Kidd. Afterall, the games are designed around fine-grained & quick analog control.
* Alex Kidd BMX Trial
* Galactic Protector
* Megumi Rescue
It works on both _Export_ and _Japan_ regions. Being noted because for some reason the game code for virtually every paddle game detects it and the controller is expected to have a different I/O interface, despite it only ever being sold in Japan.
Hopefully there isn't some weird game that throws a wrench in the works regarding that.
I wanted to also add light gun support too, but it appears the …
=> Adds Sega Master System paddle support

BizHawk.Emulation.Cores/Consoles/Sega/SMS/SMS.Input.cs
Are the TH output connections for the 2 controllers bridged? Might have been a bug in the actual game where it only clocks P1's TH and nobody noticed since it doesn't matter in the Japan region. Works now either way.
Follow up to #987
=> Fixes SMS Galactic Defender's Player 2 paddle

Assets/defctrl.json, BizHawk.Client.EmuHawk/MainForm.Designer.cs, BizHawk.Client.EmuHawk/MainForm.Events.cs, BizHawk.Emulation.Cores/Consoles/Sega/SMS/SMS.IEmulator.cs, BizHawk.Emulation.Cores/Consoles/Sega/SMS/SMS.IStatable.cs, BizHawk.Emulation.Cores/Consoles/Sega/SMS/SMS.Input.cs, BizHawk.Emulation.Cores/Consoles/Sega/SMS/SMS.cs, BizHawk.Emulation.Cores/Consoles/Sega/SMS/VDP.cs
Adds support for the light phaser (light gun) for the Sega Master System.
It technically works in both regions despite it being impossible for the light phaser work on Japanese hardware (Seemed pointless to add code that would just hard/softlock games).
If anyone asks, yes, the VDP has a register and latches it on controller VH, essentially for the sake of only the light phaser, as far as I can tell in developer documentation.
Select via _SMS_ -> _Controller Type_ -> _Light Phaser_.
Use your mouse to aim and shoot; there's no indicator other than the mouse cursor as to where you'd fire on-screen so remapping that is probably not a great idea.
* Rescue Mission
* Shooting Gallery
* Rambo III
* Space Gun (shoots up and to the right, I have no idea if the game had alignment problems on real …
=> SMS Light Phaser support

BizHawk.Emulation.DiscSystem/CDFS/EndianBitConverter.cs, BizHawk.Emulation.DiscSystem/CDFS/ISODirectoryNode.cs, BizHawk.Emulation.DiscSystem/CDFS/ISOFile.cs, BizHawk.Emulation.DiscSystem/CDFS/ISONodeRecord.cs, BizHawk.Emulation.DiscSystem/CDFS/ISOVolumeDescriptor.cs
(Green Book)
* Volume descriptors and root tree are both parsed
* Uses existing ISO9660 class structures (with a few modifications)
=> DiscSystem - CDFS classes now consume CD-I discs

Assets/defctrl.json, BizHawk.Client.EmuHawk/MainForm.Designer.cs, BizHawk.Client.EmuHawk/MainForm.Events.cs, BizHawk.Emulation.Cores/Consoles/Sega/SMS/Compat.txt, BizHawk.Emulation.Cores/Consoles/Sega/SMS/SMS.IEmulator.cs, BizHawk.Emulation.Cores/Consoles/Sega/SMS/SMS.ISettable.cs, BizHawk.Emulation.Cores/Consoles/Sega/SMS/SMS.IStatable.cs, BizHawk.Emulation.Cores/Consoles/Sega/SMS/SMS.Input.cs, BizHawk.Emulation.Cores/Consoles/Sega/SMS/SMS.cs
This might seem silly since it was a complete failure with almost no library but whatever.
- Great Ice Hockey
- Sports Pad Football
- Sports Pad Soccer
Regarding the Japan version, I honestly don't know if it's working right or not because Sports Pad Soccer is so hectic and weird. The values in the hex editor appear to be correct for the Japan region, I think.
I also moved the SMS controller type to `SyncSettings` requiring core reboot, because it seems more appropriate in retrospect.
=> Adds SEGA Sports Pad for SMS support

BizHawk.Emulation.Cores/CPUs/Z80A/NewDisassembler.cs, BizHawk.Emulation.Cores/CPUs/Z80A/Z80A.cs, BizHawk.Emulation.Cores/Consoles/Sega/SMS/MemoryMap.CodeMasters.cs, BizHawk.Emulation.Cores/Consoles/Sega/SMS/MemoryMap.EEPROM.cs, BizHawk.Emulation.Cores/Consoles/Sega/SMS/MemoryMap.ExtRam.cs, BizHawk.Emulation.Cores/Consoles/Sega/SMS/MemoryMap.Korea.cs, BizHawk.Emulation.Cores/Consoles/Sega/SMS/MemoryMap.Sega.cs, BizHawk.Emulation.Cores/Consoles/Sega/SMS/SMS.ICodeDataLogger.cs, BizHawk.Emulation.Cores/Consoles/Sega/SMS/SMS.IDebuggable.cs, BizHawk.Emulation.Cores/Consoles/Sega/SMS/SMS.cs, BizHawk.Emulation.Cores/Consoles/Sega/SMS/TerebiOekaki.cs
The Z80 disassembler reported all of the instructions as 0 bytes long so it would just print the first instruction down the entire window.
Also, breakpoints weren't setup to work at all in `SMSHawk`.
=> Fixes debugger tool for SMSHawk

Assets/defctrl.json, BizHawk.Client.EmuHawk/MainForm.Designer.cs, BizHawk.Client.EmuHawk/MainForm.Events.cs, BizHawk.Emulation.Cores/Consoles/Sega/SMS/SMS.IEmulator.cs, BizHawk.Emulation.Cores/Consoles/Sega/SMS/SMS.Input.cs, BizHawk.Emulation.Cores/Consoles/Sega/SMS/SMS.cs
I couldn't find a game that used more than 10 keys or so, since most just use _the arrow keys_, _Insert_, and _Home_, basically pretending they make up a controller, so I can't guarantee that all the keys actually work.
SG-1000 games tested:
- Girl's Garden
- Sega-Galaga
- Champion Boxing
- Actually uses more keys if you select 2 player!
Mark III Games tested:
- F-16 Fighting Falcon
- I barely have any clue what's happening in this game, but I managed to shoot at a plane so I assume it all works.
- Alex Kidd no Miracle World*
- This one is weird, it detects the keyboard, and you can start the game with it, but once it launches into the first level, it zero-outs the flags byte that includes the detected controllers and just forcibly uses the basic controller in-game.
Resolves #1059
=> Keyboard support for SG-1000/Mark III

BizHawk.Client.EmuHawk/ArgParser.cs
the command line argument parser uses `args[i].ToLower()` to capture arguments which are not only lower case characters but this way also changes the passed argument.
The PR addresses this issue for parameters (load-state, movie, dump-name, lua) where upper case characters might be used by the user.
=> fixed possible upper case problem in command line arguments parser

BizHawk.Client.Common/lua/LuaMemoryBase.cs
After changing the range check this last remaining byte could be read successfully.
local mem = mainmemory.readbyterange(0x0000,2048)
console.log(mem)
Now produces the last entry (2047) for NES games as well:
[...]
"2040": "3"
"2041": "8"
"2042": "4"
"2043": "0"
"2044": "0"
"2045": "0"
"2046": "0"
"2047": "165"
"205": "0"
"206": "176"
[...]
=> Fix for #1094 lua mainmemory.readbyterange() issue

BizHawk.Client.EmuHawk/tools/Lua/Libraries/EmuLuaLibrary.Client.cs
The Lua function `client.openrom` did not work ever since 74d1eba3689d118f4359a37fde2489ebe6267b24.
=> Lua: fix client.openrom

BizHawk.Client.Common/BizHawk.Client.Common.csproj, BizHawk.Client.Common/movie/tasproj/StateManagerDecay.cs, BizHawk.Client.Common/movie/tasproj/TasStateManager.cs, BizHawk.Client.EmuHawk/tools/TAStudio/TAStudio.MenuItems.cs, BizHawk.Client.EmuHawk/tools/TAStudio/TAStudio.cs
* Finally use exponential decay algorithm for greenzone
* Works in both directions (unlike fceux taseditor)
* Stop using last accesses states for anything
* When dropping states per project save, account for state gap better
* Use _states.Keys[i] instead of _states.ElementAt{i).Key in speedy parts, because it's apparently tons faster
* Use StateIsMarker() where it's supposed to be used
* Markers are still left untouched
* Branch states are still dead (probably forever)
=> State manager decay

Assets/Lua/UnitTests/TestCommunication_All.lua, Assets/Lua/UnitTests/TestCommunication_Simple.lua, BizHawk.Client.EmuHawk/ArgParser.cs, BizHawk.Client.EmuHawk/BizHawk.Client.EmuHawk.csproj, BizHawk.Client.EmuHawk/Communication.cs, BizHawk.Client.EmuHawk/GlobalWin.cs, BizHawk.Client.EmuHawk/MainForm.cs, BizHawk.Client.EmuHawk/tools/Lua/Libraries/EmuLuaLibrary.Communication.cs
A library which allows easier communication between Emuhawk and other programs via Lua
* Socket communication
* HTTP communication (GET/POST)
* Memory mapped files
All new functions are written in C# and exposed in Lua.
All Lua functions have "unit tests".
A simple Python package which tests the communications features is available here:
https://github.com/Ashafix/PyEmuHawk
**New Lua functions**
_SocketServerScreenShot()_
sends a screenshot to the Socket server
_SocketServerScreenShotResponse()_
sends a screenshot to the Socket server and retrieves the response
_SocketServerSend(message)_
sends a string [message] to the Socket server
_SocketServerResponse()_
receives a message from the Socket server
_SocketServerSuccessful()_
returns the status of the last Socket server action
boolean …
=> new library for communicating with other programs via Lua

BizHawk.Emulation.Cores/Consoles/Sega/gpgx64/GPGX.ISettable.cs, BizHawk.Emulation.Cores/Consoles/Sega/gpgx64/GPGX.cs
Feos closed #1167  due to what appears to have been a misunderstanding of the issue. This fixes the issue by moving the aforementioned settings into the SyncSettings
This doesn't touch "Use Custom Backdrop Color" as I'm unsure if that persisting through savestates is just a result of how the feature works internally (if the override background color is baked into the savestate), and that setting doesn't appear to break savestate consistency
=> Fix GPGX issues mentioned in #1167 by moving certain settings into the SyncSettings

BizHawk.Client.Common/PathManager.cs
FileSystemSafeName always takes in a GameInfo and some games have forward slashes in their name, resulting in the name being mishandled by FilesystemSafeName.
Currently, FileSystemSafeName does a check for the DirectoryName and the FileName as the behavior for Libretro cores is to include the name of the core as a directory. e.g. (desmume_libretro\Super Mario 64 DS).  
As Libretro cores use a backslash rather than a forward slash, this change does not break that behavior.
Fixes #1088
=> Filter out forward slashes in FileSystemSafeName. Fixes #1088

BizHawk.Emulation.Cores/BizHawk.Emulation.Cores.csproj, BizHawk.Emulation.Cores/CPUs/MOS 6502X/Disassembler.cs, BizHawk.Emulation.Cores/CPUs/MOS 6502X/Execute.cs, BizHawk.Emulation.Cores/CPUs/MOS 6502X/IMOS6502XLink.cs, BizHawk.Emulation.Cores/CPUs/MOS 6502X/MOS6502X.cs, BizHawk.Emulation.Cores/Computers/Commodore64/MOS/Chip6510.cs, BizHawk.Emulation.Cores/Computers/Commodore64/Serial/Drive1541.cs, BizHawk.Emulation.Cores/Consoles/Atari/2600/Atari2600.Core.cs, BizHawk.Emulation.Cores/Consoles/Atari/A7800Hawk/A7800Hawk.cs, BizHawk.Emulation.Cores/Consoles/Nintendo/NES/NES.Core.cs, BizHawk.Emulation.Cores/Consoles/Nintendo/NES/NES.CpuLink.cs, BizHawk.Emulation.Cores/Consoles/Nintendo/NES/NES.ICodeDataLogger.cs
This PR creates an interface (`IMOS6052XLink`) that has all the methods required for the CPU to talk to the emulator core. The `MOS6052X` then takes a type implementing this interface as a generic type parameter.
The `MOS6052X` constructor takes a link as a parameter, and uses this to talk to the emulator core, instead of the `Func`/`Action` delegates currently used. This means that the compiler knows the exact methods being called at compile time.
By making all implementations of this link interface `struct`s, the compiler can subsequently eliminate pointer chasing (the delegates live on the heap) and virtual calls (`Func.Invoke`/`Action.Invoke`).
For example, on my machine, this leads to a speedup of ~1-2 fps for NESHawk and ~7-9 fps for A2600.
This change needs some more testing across …
=> Use generic interface type on MOS 6052X for talking to the emulator core

BizHawk.Client.EmuHawk/MainForm.cs
Make it possible to resize the video even in unattended mode.
=> Resize unattended video if zoom factor >1

BizHawk.Client.EmuHawk/tools/Lua/LuaConsole.cs
Extracts the "enable" side of the Lua toggle logic and reuses it when loading a script for the first time. As this contains the drawing part, this causes Lua scripts to be drawn the first time they are loaded. Fixes #1138.
=> Draw Lua script when loading

BizHawk.Client.Common/XmlGame.cs, BizHawk.Client.EmuHawk/tools/MultiDiskBundler/MultiDiskBundler.cs, BizHawk.Client.EmuHawk/tools/MultiDiskBundler/MultiDiskFileSelector.cs
This has been bugging me for a while now.
Open ticket from 2016 - #764
This pull request does the following:
* Allows BizHawk-XMLGame files to include references to ROMs/Tapes/Disks within archives (using the same format that Bizhawk uses elsewhere). Importantly, this is parsed correctly before being sent to RomLoader further down the line (the code was kind of there, but not complete). 
XML example:
* MultiDiskFileSelector and MultiDiskBundler have been modified to call ArchiveChooser when an archive is selected through the browse dialog. There is certain conditional logic here. It will basically tell the user to FO if the selected system is PSX, PCFX or SAT (basically systems that will probably die if you try to load files from within an archive).
* The 'SaveAndRun' button on the …
=> MultiDiskBundler: Handle archive files properly

BizHawk.Emulation.Cores/Computers/Commodore64/C64.ISettable.cs, BizHawk.Emulation.Cores/Computers/Commodore64/MOS/Vic.cs
This is in relation to ticket #1272
This PR:
* Adds a 'None' border option as requested:
* Fixes the endless loop that happens in  Vic.TimingBuilder (timingbuilder is expecting -1 values for hblankStart and hblankEnd passed to it when the 'Full Border' option is selected. Without the new changes in this PR Vic.ConfigureBlanking ends up converting hblankStart and vblankStart to the same value (and actually an odd number - which is ultimately what is responsible for the infinite loop).
So basically the 'Full Border' option now works, but it actually is showing the screen including the horizontal and vertical flyback periods. I.E. : it looks weird:
Its probably safe to say that the person who raised the issue believed that FULL is what he/she wanted (but didnt know this because it never …
=> C64Hawk: Fix border issues - #1272

BizHawk.Client.Common/Global.cs, BizHawk.Client.Common/movie/conversions/MovieConversionExtensions.cs
From ticket #1246 
Small change to MovieConversionExtensions.PopulateWithDefaultHeaderValues()
Just changes SystemID to "GG" or "SG" if Global.Emulator .IsGameGear or IsSG1000 is true.
Without this, the play movie dialog shows 'Platform' as SMS for game gear and SG1000 movies (and highlights this in RED as it is incorrect).
=> Fix movie header SystemID

BizHawk.Client.EmuHawk/MainForm.cs
Reverts TASVideos/BizHawk#1205
This is terrible. It uses a hardcoded magic value that's impossible for a user to change, and it's never used anywhere in the code, to rule that all the users from now on are obliged to get 2x dumps as long as they have figured out what settings they want to use.
fix #1244
=> Revert "Resize unattended video if zoom factor >1"

BizHawk.Client.EmuHawk/tools/Lua/LuaPictureBox.cs
The lua function forms.drawText() horizontal alignment "right" did the same as "center"
=> lua: forms.drawText() horizontal alignment "right" fix

BizHawk.Client.EmuHawk/ToolAttribute.cs, BizHawk.Client.EmuHawk/tools/GameShark.cs, BizHawk.Client.EmuHawk/tools/ToolManager.cs
This is because of issue #1293 
Currently the gameshark Tool (called 'Cheat Code Converter' in the menus and dialogs) is made available to the user based on a _GlobalWin.Tools.IsAvailable`<GameShark`>()_ call. As this method only looks at the *supportedSystems* ToolAttribute, you have a situation where SNES IS supported (and the code converter dialog is made available) but the Snes9x core does not expose a 'System Bus' MemoryDomain - so exceptions are shown when the user attempts to convert a code.
This PR:
* Modifies the **ToolAttribute** class to make available an **UnsupportedCores** IEnumerable (which defaults to null)
* Modifies the **.IsAvailable(Type t)** method in **ToolManager.cs**. The logic is pretty much the same as before, except a second check is made to see whether there …
=> EmuHawk: ToolManager.IsAvailable<T>

BizHawk.Emulation.Cores/CPUs/Z80A/Operations.cs, BizHawk.Emulation.Cores/CPUs/Z80A/Tables_Direct.cs, BizHawk.Emulation.Cores/CPUs/Z80A/Z80A.cs
From ticket #1323 
@alyosha-tas : I think this should do it. Can you cast a quick eye over just to make sure you are happy (and I have not gone about things in a weird way).
It looks like IN A, (N) is the only non-ED instruction anyway, so the changes are minimal.
This fixes the 5 SMS games listed in #1323 , the games in #1267 and #1264 , and Tails Skypatrol from #1157 . 
From a speccy point of view, the timing and flag tests are also passing (along with the various ULA-related tests).
=> Z80: fix IN A, (N) flag affection

BizHawk.Client.Common/Global.cs, BizHawk.Client.EmuHawk/BizHawk.Client.EmuHawk.csproj, BizHawk.Client.EmuHawk/Input/Input.cs, BizHawk.Client.EmuHawk/Input/OTK_Gamepad.cs, BizHawk.Client.EmuHawk/Input/OTK_Keyboard.cs, BizHawk.Client.EmuHawk/Program.cs, BizHawk.Client.EmuHawk/ScreenSaver.cs, BizHawk.Client.EmuHawk/Sound/Sound.cs, BizHawk.Client.EmuHawk/Throttle.cs, Bizware/BizHawk.Bizware.BizwareGL.OpenTK/IGL_TK.cs, Bizware/BizHawk.Bizware.BizwareGL.SlimDX/IGL_SlimDX9.cs
Tested on Manjaro, Linux 4.18.0-1-MANJARO, MSBuild 15.6.0.0 (`msbuild-stable` on the AUR), Mono 5.12.0 (`extra` repo), Wine 3.11 (`multilib` repo, needed for its bundled libraries).
Changes:
- Update to latest OpenTK, add input code from `mono-portable` branch (kudos), and fix bugs arisen from version differences
- Move some functionality into Win-specific classes and add Wine+Mono implementation where simple
- Add conditions to main loop so some things only run on Windows
Steps to build and run: 
```
msbuild BizHawk.sln
cd output
ln -s dll/nlua/NLua.dll   # not sure why, but putting this in LD_LIBRARY_PATH wasn't working
LD_LIBRARY_PATH="/usr/lib/wine" mono EmuHawk.exe
```
I promise no functionality beyond Help>About.
***
Cores known to crash:
* Cygne
* Gambatte
* Genesis Plus GX
* Handy …
=> Allow 2.3 to be built and run w/ MSBuild and Wine+Mono on GNU+Linux

BizHawk.Client.EmuHawk/tools/Lua/Libraries/EmuLuaLibrary.Forms.cs, BizHawk.Client.EmuHawk/tools/Lua/Libraries/EmuLuaLibrary.Gui.cs, BizHawk.Client.EmuHawk/tools/Lua/LuaCanvas.cs, BizHawk.Client.EmuHawk/tools/Lua/LuaPictureBox.cs
In some cases, a user may want to draw a polygon at a different position without needing to update every point. The proposed changes optimize this task by applying the translation while populating the array of points.
Note that this change breaks backwards compatibility of `gui.drawPolygon`, `forms.drawPolygon`, and `LuaCanvas.DrawPolygon` by placing the new `x` and `y` parameters before `line` and `background`. This was done to maintain the convention of color arguments going last.
=> Lua: Add optional position parameters to `DrawPolygon`

Assets/Shaders/retroizer/retroizer.cg, Assets/Shaders/retroizer/retroizer.cgp, Bizware/BizHawk.Bizware.BizwareGL/RetroShader.cs
Integrates a old and used CRT Shader using scanline, distortion, ghosting, bloom and animated off-sync scanline effect similar to NES Classic Mini.
base repo was here (https://github.com/peeweek/bizhawk-shaders)
Added also Time uniform to the pipeline for the animated scanline off sync.
=> Retroizer Shader + Time uniform in custom shaders

BizHawk.Client.EmuHawk/IControlMainform.cs, BizHawk.Client.EmuHawk/MainForm.cs, BizHawk.Client.EmuHawk/tools/Debugger/GenericDebugger.IControlMainform.cs, BizHawk.Client.EmuHawk/tools/TAStudio/TAStudio.IControlMainForm.cs, BizHawk.Client.EmuHawk/tools/TAStudio/TAStudio.Navigation.cs, BizHawk.Client.EmuHawk/tools/TAStudio/TAStudio.cs
This resolves the TODO involving runFrame, which is supposed to be false when we want to be at frame zero, but is currently always true.
I don't believe it has any side effects from other code paths, and I tested it out in my own projects, but it could use a second look just to be sure
=> This fixes a bug in TAStudio where you cannot use '<'to get to frame 0

BizHawk.Client.EmuHawk/IControlMainform.cs, BizHawk.Client.EmuHawk/MainForm.cs, BizHawk.Client.EmuHawk/tools/Debugger/GenericDebugger.IControlMainform.cs, BizHawk.Client.EmuHawk/tools/TAStudio/TAStudio.IControlMainForm.cs, BizHawk.Client.EmuHawk/tools/TAStudio/TAStudio.Navigation.cs, BizHawk.Client.EmuHawk/tools/TAStudio/TAStudio.cs
This reverts PR #1371 "This fixes a bug in TAStudio where you cannot use '<'to get to frame 0", see the review:
https://github.com/TASVideos/BizHawk/pull/1371#pullrequestreview-179454301
=> Revert #1371

BizHawk.Emulation.Cores/Consoles/PC Engine/VDC.cs
So I think this should do for #1363
According to here:  http://www.emulatronia.com/doctec/consolas/pce/vdcdox.txt
DESR is only 16bit.
```
17($11) R?/W    DESR - '(DMA) Destination Address Register'
b 15-0  This register sets the destination 
address for DMA transfers.
All bits used 
(although no VRAM above $7FFF).
```
@NarryG can you test?
@zeromus can you make sure I have not been stupid?
=> PCEHawk - DESR enforce 16bit register size - #1363

BizHawk.Emulation.Cores/Consoles/Nintendo/QuickNES/QuickNES.cs
Fixes issue #1423  (reversion from #1380)
Why this fixes it? No idea. I'm assuming it has to do with the static but there's no real documentation on DynamicLibraryImportResolver
=> Fix quicknes (Fixes #1423)

BizHawk.Client.EmuHawk/MainForm.cs
This fixes #1432
A while ago in a PR, I rather naively forced `deterministic` to True when `args.Deterministic == null` in `MainForm._LoadRom()`. This broke a bunch of stuff related to how the mGBA was initialised (specifically `SkipBios` and `RTCTime()` were being handled). It also meant that all cores that don't specifically handle Deterministic Emulation within their SyncSettings (which is many/most of them looking at it) always had DE set to TRUE with no possibility of being able to use frame or audio skip.
This PR reverts determinism handling in MainForm back to how it was:
* If `Global.MovieSession.QueuedMovie != null` then `deterministic = true`
* If `args.Deterministic != null` then `deterministic = args.Deterministic`
* Otherwise, `deterministic = false`
Basically, if there is a …
=> EmuHawk: _LoadRom() - Change deterministic back to how it was before. 

BizHawk.Emulation.Cores/Consoles/Nintendo/NES/Boards/Mapper034.cs
Someone was doing a TAS of Lizard and frequently causing the game to trigger its "crash" handler:
https://twitter.com/Choaslegion00/status/1084376804171939841
Appears to be due to the PRG bank not being Synced whenever a savestate is used. This patch should clear it up, I think?
=> NES Mapper034.s is missing SyncState

BizHawk.Client.DiscoHawk/DiscoHawkDialog.cs, BizHawk.Client.EmuHawk/tools/BasicBot/BasicBot.cs, BizHawk.Emulation.Cores/CPUs/LR35902/Operations.cs, BizHawk.Emulation.Cores/CPUs/Z80A/Operations.cs, BizHawk.Emulation.Cores/Computers/SinclairSpectrum/Media/Tape/PZX/PzxConverter.cs, BizHawk.Emulation.Cores/Consoles/Atari/A7800Hawk/A7800Hawk.cs, BizHawk.Emulation.Cores/Consoles/Nintendo/GBHawk/Mappers/Mapper_MBC1_Multi.cs, BizHawk.Emulation.Cores/Consoles/Nintendo/GBHawk/Mappers/Mapper_MBC2.cs, BizHawk.Emulation.Cores/Consoles/Nintendo/GBHawk/Mappers/Mapper_MBC3.cs, BizHawk.Emulation.Cores/Consoles/Nintendo/GBHawk/Mappers/Mapper_MBC7.cs, BizHawk.Emulation.Cores/Consoles/Nintendo/NES/Boards/Cony.cs, BizHawk.Emulation.Cores/Consoles/Nintendo/NES/Boards/Mapper222.cs, BizHawk.Emulation.Cores/Consoles/Nintendo/NES/PPU.cs, BizHawk.Emulation.Cores/Consoles/Sega/gpgx64/GPGX.IVideoProvider.cs
I'll do something more helpful next, I promise.
Edit: to save you the trouble, the commit desc is "Remove useless semicolon, remove useless `? true : false`, move period to next line". Pretty self-explanatory stuff.
***
I've got a list of things like this that aren't removed pre-compile, the last few might be controversial. Input on what is and isn't project convention would be appreciated so I have something to do while Mono work is being tested.
* `"a" + b + "c"` -> `$"a{b}c"`
* `String.Format("a {0} c", b)` -> `$"a{b}c"` (I think this can't be done in some places)
* `Type Property { get; }` -> `readonly Type Property` where possible
* renaming files where it doesn't match the contained class name, excluding partial classes ofc
* LF -> CRLF, not sure how LFs happened in a Windows …
=> Inconsequential changes (no whitespace)

BizHawk.Client.Common/config/Config.cs
And work around unimplemented stuff in the System.Drawing implementation that I'm using
=> Use SystemColors, not Color.FromName() to avoid the extra hop

BizHawk.Client.Common/tools/Watch/ByteWatch.cs, BizHawk.Client.Common/tools/Watch/DWordWatch.cs, BizHawk.Client.Common/tools/Watch/WordWatch.cs, BizHawk.Emulation.Cores/CPUs/Z80A/NewDisassembler.cs
[MSDN](https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-numeric-format-strings#the--section-separator) (scroll up, their anchors don't seem to work)
Vastly simplifies these methods. May also simplify [Timestamp.Value getter](https://github.com/TASVideos/BizHawk/blob/a0e623ef1b5dbbb6bcc0b9f51414fcab9b526c42/BizHawk.Emulation.DiscSystem/DiscTypes.cs#L138) and [Sprintf.FormatNumber](https://github.com/TASVideos/BizHawk/blob/ebe789eed22954d1eb40a0ef0a5937181739e1c3/BizHawk.Common/Sprintf.cs#L633) but that would require touching more code.
Edit edit: Fixed, but had to forego the semicolons in Z80 disasm because it's hex and you apparently can't mix custom and preset formats.
=> [Untested] Use format strings with the semicolon section separator

BizHawk.Client.EmuHawk/tools/Lua/Libraries/EmuLuaLibrary.Client.cs
Two new functions for the Lua `client` module, addresses #1177 
* sleep
* exactsleep
Both functions freeze the whole emulator for n milliseconds. `sleep` is a bit more imprecise but uses less resources, `exactsleep` is precises but eats CPU resources.
=> Added sleep functions for Lua to client module (resolves #1177)

BizHawk.Common/Serializer.cs, BizHawk.Common/Util.cs
As the title says.
Implements required logic to serialize and deserialize double values and double arrays, along with float arrays. Works with both binary and text sync modes.
It uses Buffer.BlockCopy for the array stuff (hopefully this is quick enough).
=> Serializer: Add support for float[], double and double[]

BizHawk.Client.EmuHawk/ArgParser.cs, BizHawk.Client.EmuHawk/MainForm.cs
Based on the discussion here #1398 it seemed like a good idea to be able to set 'alternate sync' in movie settings via the command line. Use case for me would be to create PNG imageseries from multiple movie files. Currently I need to do it manually since `alternate sync` is enabled by default.
Not sure about the best name for this parameter, internally it is called `VideoWriterAudioSync ` but in the user interface it is called `alternate sync`.
=> added new command line parameter audiosync

BizHawk.Client.ApiHawk/Classes/ClientApi.cs, BizHawk.Client.Common/tools/Watch/ByteWatch.cs, BizHawk.Client.Common/tools/Watch/DWordWatch.cs, BizHawk.Client.Common/tools/Watch/WordWatch.cs, BizHawk.Client.DBMan/DATTools/DATConverter.cs, BizHawk.Client.DBMan/DATTools/NOINTROParser.cs, BizHawk.Client.DBMan/DATTools/TOSECParser.cs, BizHawk.Client.DBMan/DB.cs, BizHawk.Client.DBMan/RomHasher.cs, BizHawk.Client.EmuHawk/config/NES/NESSyncSettingsForm.cs, BizHawk.Client.EmuHawk/tools/Debugger/GenericDebugger.Disassembler.cs, BizHawk.Client.EmuHawk/tools/NES/NESMusicRipper.cs, BizHawk.Client.EmuHawk/tools/SNES/SNESGraphicsDebugger.cs, BizHawk.Client.EmuHawk/tools/TraceLogger.cs, BizHawk.Client.MultiHawk/Input/GamePad.cs, BizHawk.Client.MultiHawk/Input/Input.cs, BizHawk.Client.MultiHawk/Mainform.cs, BizHawk.Client.MultiHawk/movie/PlayMovie.cs, BizHawk.Common/Extensions/BufferExtensions.cs, BizHawk.Common/Extensions/NumberExtensions.cs, BizHawk.Emulation.Cores/CPUs/Z80A/Z80A.cs, BizHawk.Emulation.DiscSystem/DiscFormats/Blobs/RiffMaster.cs
Everything that didn't make the other PRs.
~~[This needs review](https://github.com/TASVideos/BizHawk/blob/e6374ef4771ff0f0b973bd5f671675269e3f7a96/BizHawk.Client.EmuHawk/tools/SNES/SNESGraphicsDebugger.cs#L728)~~ clearly [copied from the line above](https://github.com/TASVideos/BizHawk/commit/3dd1c5c493d16a90264ab3d0a884c3c6f59d92fc#diff-a1d4c970bc553c6c0a85f7c2cb2ac433R695) and the unnecessary `string.Format` call was never removed. edit: after fixing that, appveyor stopped building this branch ¯\\\_(ツ)\_/¯
=> Remaining string interpolation (excluding BizHawk.Emulation.Cores)

BizHawk.Client.Common/BizHawk.Client.Common.csproj, BizHawk.Client.Common/input/PolarRectConversion.cs, BizHawk.Client.EmuHawk/tools/VirtualPads/controls/VirtualPadAnalogStick.cs
I fixed the polar magnitude only decreasing in the event handler (?), there's still the issue of the polar numboxes not being updated when the rectangular ones are. Clicking on the ellipse works fine.
Having a pre-determined mapping from polar to rect and vice-versa might be a good idea, as it stands there are fractions being cut off everywhere. Something like `static readonly (uint, uint)[,] r2p` and `static readonly (int, int)[,] p2r`, used like `(x, y) = p2r[r][θ]` should work (currently tuple boilerplate is needed, also indices are positive so rectangular coords would need to be translated first).
~~hopefully I'll get around to #581~~ will open new PR
=> Polar stuff

BizHawk.Emulation.Cores/Computers/AmstradCPC/Hardware/Display/CRCT_6845.cs, BizHawk.Emulation.Cores/Computers/AmstradCPC/Hardware/Display/CRTC6845.cs, BizHawk.Emulation.Cores/Consoles/Nintendo/GBHawk/MemoryMap.cs, BizHawk.Emulation.Cores/Consoles/Nintendo/NES/PPU.regs.cs
Someone's IDE put smart tabs in comments:
=> Fix tables in comments with mixed whitespace

BizHawk.Emulation.Cores/Sound/YM2413.cs
edit: PR would previously replace jagged arrays with multidimensional ones. It theoretically caused a tiny performance hit but saved a tiny bit of memory, however it was deemed no easier to read so I did this inlining instead.
=> Inline a static multidimensional array

BizHawk.Client.EmuHawk/tools/SNES/SNESGraphicsDebugger.cs
Fixes an issue that caused the TM and TS checkboxes for the OBJ layer to
always be the opposite of what is correct.
=> Fix TM and TS checkboxes for OBJ in SNES Graphics Debugger

Assets/gamedb/gamedb_goodnes.txt, BizHawk.Emulation.Common/Database/Database.cs
Some game names in gamedb files are HTML-encoded. This change decodes those game names so they display properly in BizHawk's title bar  (resolves #1667).
=> Use WebUtility.HtmlDecode() to decode game names

Assets/Lua/GBA/SonicAdvance_CamHack.lua, BizHawk.Client.EmuHawk/MainForm.cs, BizHawk.Client.EmuHawk/tools/Lua/Libraries/EmuLuaLibrary.Client.cs, BizHawk.Emulation.Cores/Consoles/Nintendo/GBA/MGBAHawk.ISoundProvider.cs, BizHawk.Emulation.Cores/Consoles/Nintendo/GBA/MGBAHawk.IVideoProvider.cs, BizHawk.Emulation.Cores/Consoles/Nintendo/GBA/MGBAHawk.cs, BizHawk.Emulation.Cores/Consoles/Sega/gpgx64/GPGX.IEmulator.cs
https://www.youtube.com/watch?v=uFl0ax-GYk8
For a test, mGBA core uses fake video and audio buffers and renders to them when we want to "skip" rendering. Proper setup would involve actually skipping rendering those inside the core.
For the camhack to work we have to save a state, hack memory, advance twice to see the changes, then load the state to prevent desync. Since we can omit the framebuffer in savestates, loading them can happen without updating the screen, so the hacked camera remains visible.
Advancing 2 frames automatically is done like tastudio does it when it seeks to a frame, only from lua now.
And the most questionable part is "invisible emulation", which is how Gens calls this IIRC, when everything that can distract or slow us down is skipped: sound, video, tools updates. …
=> Camhack support

BizHawk.Client.Common/lua/EmuLuaLibrary.Events.cs, BizHawk.Emulation.Common/Base Implementations/MemoryCallbackSystem.cs
I'm trying to get this [arcane cycle-counting Lua script](https://cdn.discordapp.com/attachments/606046567232831500/653498902967746570/rm1delay_bizhawk.lua) working on BizHawk so we can get guaranteed console-valid Mega Man TASes. There's a race condition that lets you execute arbitrary code, and this script needs a callback on every cycle to determine when it will happen.
I find it suspicious that this behavior was specifically checked for and blocked. But whatever problems it has, it can't be worse than when I tried to individually register 65,536 callbacks! Right...?
For reference, here's the [original script](https://cdn.discordapp.com/attachments/516260276425981952/653457271006691334/rm1delay_rev6.lua), as seen on FCEUX, and my …
=> All Memory Execute

BizHawk.Client.EmuHawk/tools/Macros/MacroInput.cs, BizHawk.Client.EmuHawk/tools/Macros/MovieZone.cs, BizHawk.Client.EmuHawk/tools/TAStudio/TAStudio.MenuItems.cs, BizHawk.Client.EmuHawk/tools/TAStudio/TAStudio.cs
All macro tools will fail due to the `MovieZone` class not populating the `FloatRanges` property of the `ControllerDefinition` objects it creates (if the current core has float inputs). If this issue is fixed, more issues arise however.
The second major issue is that the `MovieZone` constructor that is used for macros uses fields (`_emulator`, `_tools`) does not supply these fields.
Related to the last problem is that the menu items in TAStudio that perform macro functionality basically bypass actually showing the macro tool form, but call functions on the form. Since the form is not instantiated correctly via a standard `Load` call, some more stuff breaks. Creating the form with the `Load` calls however causes the macro tool form to show when clicking on menu items.
All of this is to say …
=> Fix Macro Functionality (fixes #1838)

BizHawk.Client.EmuHawk/AVOut/FFmpegWriter.cs
There is a known bug in the `Process.WaitForExit(time)` overload ([see remarks here](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.process.waitforexit?view=netframework-4.8#System_Diagnostics_Process_WaitForExit_System_Int32_)). This method will wait for the process to exit but it will _not_ wait for the message pump for that process to finish dealing with events. This was causing a race condition for ffmpeg processes that were trying to write to stderr around the same time that the process variables are being nulled in `CloseFileSegment()`. 
This problem occurs much more frequently with hardcore debug mode due to switching resolutions causing file segments to get opened/closed frequently. The bug is still frustratingly inconsistent to reproduce though.
To my …
=> Fix ffmpeg race condition.

BizHawk.Client.Common/lua/EmuLuaLibrary.Joypad.cs
The current implementation for this function tries to coerce passed values into floats:
https://github.com/TASVideos/BizHawk/blob/096277122553d38d87fa11c0cfe4d45e2682b939/BizHawk.Client.Common/lua/EmuLuaLibrary.Joypad.cs#L52-L59
However, the indexing operator for LuaTable returns `object`, causing this line to be interpreted as *unboxing* the table value to a `float`.
By [old](https://www.lua.org/pil/2.3.html) and [new](https://www.lua.org/manual/5.3/manual.html#lua_Number) spec, Lua numbers are expected to be implemented to double precision by default, and this is true for the `NLua+KopiLua` and `Lua+LuaInterface` implementations, so the value returned by `controls[k]` ends up being a `double` boxed as `object`.
Attempting to unbox `double` as `float` throws a …
=> Fix InvalidCastException in JoypadLuaLibrary.SetAnalog

BizHawk.Client.Common/Api/Classes/JoypadApi.cs, BizHawk.Client.Common/lua/EmuLuaLibrary.Joypad.cs, BizHawk.Emulation.Common/Extensions.cs
See https://github.com/TASVideos/BizHawk/issues/1897
At some point from 2.2.1 to now, joypad.set() no longer works properly. The following no longer works when it used to:
```
-- Example #1
local input =  {["A"] = true}
joypad.set(input, 1) -- Does nothing when it used to work in 2.2.1
-- Example #2
local input = {["A"] = 1}
joypad.set(input, 1) -- Throws exception when it used to work in 2.2.1
local input = {["P1 A"] = true}
joypad.set(input) -- Interestingly, this still works
```
This pull request fixes the first two scenarios. The main issue was with this block of code:
```
public void Set(Dictionary<string, bool> buttons, int? controller = null)
{
foreach (var button in Global.InputManager.ActiveController.Definition.BoolButtons)
{
Set(button, buttons.TryGetValue(button, out var …
```
=> Fixes joypad.set() method in Lua Console

BizHawk.Emulation.Cores/Consoles/Nintendo/Gameboy/GBColors.cs
New GBC LCD correction for Gambatte palette from documented shader research https://forums.libretro.com/t/real-gba-and-ds-phat-colors/1540
Extrems uses this same correction in GBI and helped port it to BizHawk-Gambatte.
I would suggest that this should at least be a new default if not replacing the Gambatte palette completely as in my repo.  We don't really know what Sinamas' Gambatte palette is trying to do, it doesn't match documented behavior of the GBC LCD.
=> Fix the Gambatte Palette

src/BizHawk.Client.EmuHawk/MainForm.cs, src/BizHawk.Emulation.Cores/Consoles/Belogic/Uzem.cs, src/BizHawk.Emulation.Cores/Consoles/NEC/PCFX/Tst.cs, src/BizHawk.Emulation.Cores/Consoles/Nintendo/Gameboy/Sameboy.cs, src/BizHawk.Emulation.Cores/Consoles/Nintendo/SNES/LibsnesApi.cs, src/BizHawk.Emulation.Cores/Consoles/Nintendo/SNES9X/Snes9x.cs, src/BizHawk.Emulation.Cores/Consoles/Nintendo/VB/VirtualBoyee.cs, src/BizHawk.Emulation.Cores/Consoles/SNK/NeoGeoPort.cs, src/BizHawk.Emulation.Cores/Consoles/Sega/PicoDrive/PicoDrive.cs, src/BizHawk.Emulation.Cores/Consoles/Sega/Saturn/Saturnus.cs, src/BizHawk.Emulation.Cores/Consoles/Sega/gpgx64/GPGX.cs, src/BizHawk.Emulation.Cores/Waterbox/PeRunner.cs
=> Make waterbox consistency check ui option only skip the memory check, not the core check

src/BizHawk.Client.Common/Api/Classes/MovieApi.cs, src/BizHawk.Client.Common/Api/Interfaces/IInputMovie.cs, src/BizHawk.Client.Common/movie/HeaderKeys.cs, src/BizHawk.Client.Common/movie/bk2/Bk2Movie.HeaderApi.cs, src/BizHawk.Client.Common/movie/bk2/Bk2Movie.InputLog.cs, src/BizHawk.Client.Common/movie/bk2/Bk2Movie.cs, src/BizHawk.Client.Common/movie/interfaces/IMovie.cs, src/BizHawk.Client.EmuHawk/MainForm.FileLoader.cs
This was a gimmick feature a long time ago, and has only been used twice to my knowledge.  It's a feature that would never lead to a tasvideos publication. 
It isn't that much code, but it does complicate the api (such as frame count being a double).  If we were to expand capabilities to include subframe input, this feature would actively complicate the implementation.
It was fun, but I think maybe it is time to go, what do people think?
=> Remove infinity movies

src/BizHawk.Client.EmuHawk/tools/HexEditor/HexEditor.cs, src/BizHawk.Emulation.Common/Base Implementations/MemoryDomain.cs
The existing API was such that BulkPeekUint(Start: 20, EndInclusive: 39) would actually read from the address range [20, 100) instead of [20, 40).  That's completely broken.  The hex editor, the only consumer of the API, made the same exact mistake in reverse so the problem wasn't immediately apparent, but it was a giant land mine waiting to happen.  Fix them both.
=> Fix hex editor bulk multibyte reads

src/BizHawk.Client.Common/RomLoader.cs, src/BizHawk.Client.Common/config/Config.cs, src/BizHawk.Client.EmuHawk/MainForm.Designer.cs, src/BizHawk.Client.EmuHawk/MainForm.Events.cs
We should not give the user the ability to turn this off.  If they are power users and want to overwrite our db, they can mod the db entries
=> remove CoreForcingViaGameDb user option.  

src/BizHawk.Emulation.Common/Database/FirmwareDatabase.cs
Updated the msx bios filename based on mame 0.221 and cbios0.29a, this way it fixes the filename conflict while using the feature "Organize" through Firmware Manager.
Couldn't figure it out about the bios_test origin, so I kept that one unchanged.
=> update msx bios filenames and description

src/BizHawk.Client.Common/tools/Cheat.cs, src/BizHawk.Emulation.Common/Base Implementations/MemoryDomain.cs, src/BizHawk.Emulation.Common/Base Implementations/MemoryDomainImpls.cs, src/BizHawk.Emulation.Cores/Consoles/Nintendo/NES/NES.Core.cs, src/BizHawk.Emulation.Cores/Consoles/Nintendo/NES/NES.IMemoryDomains.cs
Here is a PR that gets Game Genie compare cheats working properly in NESHawk.
It's applicability is limited to this specific case. Other compare cases (ex greater then) still do not work, as do other cheats outside of this scope (ex RAM.)
But having said that, I think the implementation is reasonably clean for what it does. I needed to make a new memory domain builder class specifically for NESHawk sys. bus so that no other cores are effected by this change, but other then that not many changes were needed.
Also performance isn't so bad. Even though it checks every ROM access, it only loses about 5% performance, so still can run comfortably at at least double speed for a small number of cheats (at least on my laptop.)
I purposely made the scope of this very narrow, but I think that's fine …
=> NESHawk: make game genie compare cheats work

src/BizHawk.Client.EmuHawk/MainForm.Designer.cs, src/BizHawk.Client.EmuHawk/MainForm.Events.cs, src/BizHawk.Client.EmuHawk/MainForm.cs, src/BizHawk.Client.EmuHawk/tools/ToolManager.cs, src/BizHawk.Emulation.Common/CoreAttribute.cs, src/BizHawk.Emulation.Common/Extensions.cs, src/BizHawk.Emulation.Cores/Arcades/MAME/MAME.cs, src/BizHawk.Emulation.Cores/Computers/MSX/MSX.cs, src/BizHawk.Emulation.Cores/Consoles/Atari/2600/Atari2600.cs, src/BizHawk.Emulation.Cores/Consoles/GCE/Vectrex/VectrexHawk.ISettable.cs, src/BizHawk.Emulation.Cores/Consoles/GCE/Vectrex/VectrexHawk.cs, src/BizHawk.Emulation.Cores/Consoles/Magnavox/Odyssey2/O2Hawk.cs, src/BizHawk.Emulation.Cores/Consoles/NEC/PCFX/Tst.cs, src/BizHawk.Emulation.Cores/Consoles/Nintendo/GBHawkLink/GBHawkLink.cs, src/BizHawk.Emulation.Cores/Consoles/Nintendo/GBHawkLink3x/GBHawkLink3x.cs, src/BizHawk.Emulation.Cores/Consoles/Nintendo/GBHawkLink4x/GBHawkLink4x.cs, src/BizHawk.Emulation.Cores/Consoles/Nintendo/VB/VirtualBoyee.cs, src/BizHawk.Emulation.Cores/Consoles/SNK/NeoGeoPort.cs, src/BizHawk.Emulation.Cores/Consoles/Sega/GGHawkLink/GGHawkLink.cs, src/BizHawk.Emulation.Cores/Consoles/Sega/Saturn/Saturnus.cs, src/BizHawk.Emulation.Cores/Consoles/WonderSwan/WonderSwan.cs
Make a generic core menu that includes a Settings menu item that opens a GenericCoreConfig dialog.  Remove a lot of hardcoded menus that only did this.  Default to this, if system id is not recognized.
This reduces a lot of boilerplate code that is necessary to spin up a new core.  And we can make this more clever later on and remove other hardcoded menu items (such as dynamically adding core specific tool dialogs)
=> Create a generic core menu

src/BizHawk.Client.Common/tools/Watch/WatchList/WatchList.cs, src/BizHawk.Client.EmuHawk/tools/Watch/RamWatch.cs
Fixes two issues relating to duplicate Ram Watches
- Because equality is checked only by address, domain and size, if there is multiple Ram Watches present, deleting one would always delete the first one
- The "Duplicate Watch" dialog would silently discard a ram watch if its address was identical to the previous one. This changes the behaviour of AddRange of WatchList, but as the method is used only here, this should be safe.
=> Fix handling of duplicate Ram Watches

src/BizHawk.Client.Common/tools/RamSearchEngine/IMiniWatch.cs, src/BizHawk.Client.Common/tools/RamSearchEngine/IMiniWatchDetails.cs, src/BizHawk.Client.Common/tools/RamSearchEngine/RamSearchEngine.cs, src/BizHawk.Client.Common/tools/Watch/ByteWatch.cs, src/BizHawk.Client.Common/tools/Watch/DWordWatch.cs, src/BizHawk.Client.Common/tools/Watch/SeparatorWatch.cs, src/BizHawk.Client.Common/tools/Watch/Watch.cs, src/BizHawk.Client.Common/tools/Watch/WordWatch.cs, src/BizHawk.Client.DiscoHawk/BizHawk.Client.DiscoHawk.csproj, src/BizHawk.Client.EmuHawk/tools/Watch/RamSearch.cs, src/BizHawk.Client.EmuHawk/tools/Watch/RamWatch.cs, src/BizHawk.Client.EmuHawk/tools/Watch/WatchEditor.cs
Various fixes relating to RAM Watch Domains and Display
* Added an `IsValid` property to `Watch`, which is used to determine if a RAM watch is within range
* If a RAM watch is out of range, "-" is displayed
* Pokes on out of range watches no longer do anything
* `IMiniWatch` and `IMiniWatchDetails` have been adjusted in a similar way, however, out of range behaviour cannot be tested because loading from .wchs is broken.
* Display Type Binary on 32-bit watches was the same as Unsigned, this was fixed
* Changing a watch's size to one where the display type is incompatible (e.g. 32 bit float -> 16 bit unsigned) resulted in a exception, this was also fixed
Possible extensions:
* Disable Poke dialog entirely on out of range watches
* Always filter Out of Range addresses with any Ram Search …
=> RAM Watch Domain Fixes

src/BizHawk.Client.Common/movie/bk2/Bk2Movie.HeaderApi.cs, src/BizHawk.Client.Common/movie/bk2/Bk2Movie.IO.cs, src/BizHawk.Client.Common/movie/tasproj/TasMovie.IO.cs
Split off from my ill-constructed #2193, which had its purpose muddied by the differently-motivated changes presented here.
Before I implemented my direct goal of altering emuVersion, I found a significant redundancy between Bk2Movie and TASMovie's Load() that seemed necessary to correct before adding new behavior. Along with significantly reducing the amount of code to maintain (removing almost 100 lines), the first change also makes Bk2 and TASMovie behavior more consistent:
- Duplicate keys in the header now use the first value given ([previously Bk2Movie-specific](https://github.com/TASVideos/BizHawk/commit/dd28c386de642e7858d910b7f53e9144f2bc2cbb)). Incidentally, testing exposed a race condition between rerecords and rendering related to this, which could have caused movie's rerecord …
=> Merge redundant copy-pasted movie loading code.

src/BizHawk.Client.Common/movie/HeaderKeys.cs, src/BizHawk.Client.Common/movie/MovieConversionExtensions.cs, src/BizHawk.Client.Common/movie/bk2/Bk2Movie.HeaderApi.cs, src/BizHawk.Client.Common/movie/bk2/Bk2Movie.IO.cs, src/BizHawk.Client.Common/movie/interfaces/IMovie.cs, src/BizHawk.Client.EmuHawk/movie/PlayMovie.cs
This main goal is to address #2152. There are a few alternatives to the specific implementation I propose here:
1) As feos suggested, maintain a list of all emulator versions that have edited a movie. This could be a set or a sequential list.
2) Don't even maintain OriginalEmuVersion as a field, and move it to the Comments, in the same way as some information from converted movies is stored. This has the downside of automatically populating comments for every new movie created.
3) Just don't even keep OriginalEmuVersion. Not preferrable in my opinion, because it's interesting info and may be useful to get back in some cases.
=> Keep emuVersion up-to-date when saving movies

src/BizHawk.Emulation.Common/Interfaces/Services/ISettable.cs
This would fail to work on any core that used the serviceprovider to provide a settings definition that wasn't on the iemulator itself?  Guess we never did that
=> Fix issue with settings adapter

src/BizHawk.Emulation.DiscSystem/DiscIdentifier.cs
Seems like PS2 games have an appId of PLAYSTATION sometimes, so move the SYSTEM.CNF;1 check first
=> Reorder the optical disk id checks

src/BizHawk.Client.Common/Api/Classes/MemoryApi.cs
I don't know if there was any actual reason for having Lua read and write stuff one byte at a time.
However, this causes it to completely fail in cases where the core rejects single-byte operations.
Example: Writing to VRAM with MelonDS. The attached Lua script works on this branch, but not on master. It is for the game New Super Mario Bros..
[NSMB Input.txt](https://github.com/TASVideos/BizHawk/files/5018453/NSMB.Input.txt)
The relevant file seems like a mess to me, and maybe it should be completely redone, but I don't feel like doing that right now.
=> Lua 16/32-bit read/write

src/BizHawk.Client.Common/movie/interfaces/IMovie.cs, src/BizHawk.Client.Common/movie/tasproj/IStateManager.cs, src/BizHawk.Client.Common/movie/tasproj/TasMovie.Editing.cs, src/BizHawk.Client.Common/movie/tasproj/TasMovie.cs, src/BizHawk.Client.Common/movie/tasproj/ZwinderStateManager.cs
To start with, 770ddc26dbd987262790158206d475c6e5abe3ee (6 years ago, prior to 1.7.0) made the documentation of how truncate is supposed to work. However, judging by my testing of 1.9.0 and 2.4.2, it probably hasn't ever worked that way in practice. It seems justified to change the documentation to match the behavior that the user is familiar with, and what I see as the commonsense behavior anyway (I can justify this further if anyone is curious).
Note this is not changing the behavior of truncate itself; it is simply documenting what the behavior has always been.
Secondly, Invalidate was modified to become InvalidateAfter. This modifies how it gets called, but otherwise remains mostly identical internal to the Zwinder. This was done to make it easier to reason about relative to the input …
=> Clean up truncate behavior and docs. Fixes #2285

src/BizHawk.Client.Common/movie/tasproj/IStateManager.cs, src/BizHawk.Client.Common/movie/tasproj/TasMovie.IO.cs, src/BizHawk.Client.Common/movie/tasproj/TasMovie.cs, src/BizHawk.Client.Common/movie/tasproj/TasMovieMarker.cs, src/BizHawk.Client.Common/movie/tasproj/ZwinderStateManager.cs, src/BizHawk.Client.Common/movie/tasproj/ZwinderStateManagerSettings.cs, src/BizHawk.Client.Common/rewind/ZwinderBuffer.cs, src/BizHawk.Client.EmuHawk/tools/TAStudio/BookmarksBranchesBox.cs, src/BizHawk.Tests/Client.Common/Movie/ZwinderStateManagerTests.cs
A lot of fixes and refactors here.
1) Rename ancient to reserved and make it a dictionary
2) roll frameZeroState into the reserved section
3) roll bookmark states into reserved
4) add a reserved callback that the client code can pass in, that will check this and put things in reserved rather than evict them,
client code will check if marker or branch state
4) refactor assumptions about reserved always being states before current or recent
5) add a gapFiller, that will do the job highPriority was badly doing, and do it better
6) add a state cache that keeps track of all frames that have a state, use this in HasState, for a huge performance boost, compared to both the previous zwinder code and the old state manager, both had a O(n) problem, where performance slowed down greatly as the size …
=> Majorly refactor ZwinderStatemanager to address # 2287

src/BizHawk.Client.Common/RomLoader.cs
When a missingfirmwareexception is encountered, do not fallback.  It's presumed that these cases are fixable by the end user.
Absolutely does not in any way fix #2327 - the user was emphatic that they had the BIOS file, so they must have hit some other situation.
=> rohmloader tweak

src/BizHawk.Client.Common/movie/tasproj/TasMovie.Editing.cs
The problem occurs when trying to delete a selection where some of the frames were valid, but the last displayed line (which is currently an extra non-input frame) was in the selection.
=> TAStudio: Fix deletion crashing when deleting invalid indexes

src/BizHawk.Client.Common/config/ConfigService.cs, src/BizHawk.Client.EmuHawk/MainForm.cs, src/BizHawk.Client.EmuHawk/Program.cs
edit: Force-pushed with bugfixes and extra cleverness for 2.4.1 and 2.4.2, which identify themselves as 2.4.0.
edit 2: If you want to test this, set `DeveloperBuild` to `false` in `VersionInfo`, and edit the strings near the bottom of `config.ini` (you can also use `Config` > `Load Config From...`). If you want to see all the messages, set `MainVersion` to `2.5.1`. Then { `` (delete the keys), `2.3.3`, `2.4.0`, `2.5`, `2.5.2` } will trigger each of the 5 cases.
=> Add warning for loading config.ini from an older or newer version

src/BizHawk.Emulation.Cores/Consoles/Nintendo/GBA/LibmGBA.cs, src/BizHawk.Emulation.Cores/Consoles/Nintendo/GBA/MGBAHawk.IMemoryDomains.cs, src/BizHawk.Emulation.Cores/Consoles/Nintendo/GBA/MGBAHawk.cs
Fixes #1620
Before merging this, https://github.com/TASVideos/mgba/pull/4 should be accepted, and the submodule and dlls should be updated with the newest mGBA.
=> mGBA: Update SaveRAM mem domain to a hardcoded size. 

src/BizHawk.Client.Common/Controller.cs, src/BizHawk.Client.EmuHawk/tools/TAStudio/TAStudio.ListView.cs, src/BizHawk.Emulation.Common/Base Implementations/Axes/AxisSpec.cs, src/BizHawk.Emulation.Cores/Consoles/Nintendo/GBA/MGBAHawk.cs
Binding host gamepad sticks to virtual sticks should work the same as before, bar typos. Binding host gamepad sticks and triggers to virtual triggers (or trigger-like axes e.g. light sensor) was changed. I think it's an improvement.
edit: Just spotted a division by zero bug, but it was present in the old code too so ¯\\\_(ツ)_/¯
merging closes #2323
=> Fix scaling of axes

src/BizHawk.Client.EmuHawk/AVOut/IVideoWriter.cs, src/BizHawk.Client.EmuHawk/Api/ApiManager.cs, src/BizHawk.Client.EmuHawk/MainForm.cs, src/BizHawk.Client.EmuHawk/Program.cs, src/BizHawk.Client.EmuHawk/config/EmuHawkOptions.cs, src/BizHawk.Client.EmuHawk/tools/Lua/Win32LuaLibraries.cs, src/BizHawk.Client.EmuHawk/tools/ToolBox.cs, src/BizHawk.Client.EmuHawk/tools/ToolManager.cs, src/BizHawk.Client.EmuHawk/tools/VirtualPads/VirtualpadsTool.cs, src/BizHawk.Common/Util.cs
I'd like get the dep removed for 2.5. If someone has a better solution to this (other than having separate releases and using conditional compilation) I'd be all for it.
=> Technical changes for dropping VB.NET dep on Unix

src/BizHawk.Client.EmuHawk/CustomControls/InputRoll/InputRoll.cs, src/BizHawk.Client.EmuHawk/CustomControls/InputRoll/RollColumn.cs, src/BizHawk.Client.EmuHawk/tools/TAStudio/BookmarksBranchesBox.cs, src/BizHawk.Client.EmuHawk/tools/TAStudio/MarkerControl.cs, src/BizHawk.Client.EmuHawk/tools/TAStudio/TAStudio.MenuItems.cs, src/BizHawk.Client.EmuHawk/tools/TAStudio/TAStudio.cs
See also: #2215
The previous work intended to implement multi-select for 2.5 doesn't quite work right, so I'm trying to fix it here.
Known issues:
=> Markers/branch multi-selection

Assets/EmuHawkMono.sh
Pop_OS is a Linux distro based on Ubuntu. I added it to the Unix launch shell script in order to remove an error message I received.
=> Added Pop_OS support for library paths

src/BizHawk.Client.Common/movie/bk2/Bk2Movie.IO.cs
Should be correct and I have tested this to confirm it does what it should
=> Fix tasproj backup files getting saved with savestates / greenzone

src/BizHawk.Emulation.Common/Database/FirmwareDatabase.cs
Change the status of alternate GB/C firmware options to unacceptable. Quoting from CasualPokePlayer "Gambatte is definitely not emulating those cpus [dmg0 and cgb0]. So you would end up with quirks of newer cpus being combined with bootroms only present in older cpus."
Also fix what looks to be a longstanding typo where the PCFX BIOS v1.01 was not being properly detected.
=> Minor GB/C and PCFX firmware detection revisions

src/BizHawk.Client.EmuHawk/config/ProfileConfig.cs, src/BizHawk.Emulation.Cores/Consoles/Nintendo/Gameboy/Gambatte.ISettable.cs, src/BizHawk.Emulation.Cores/Consoles/Nintendo/Gameboy/Gambatte.cs
Having GBA be a console mode is more straightforward for users to understand and a more logical way of arranging options. GBA is literally a console mode, not an additional modifier to a console mode.
=> Simplify Gambatte's sync settings for selecting GBA

src/BizHawk.Client.Common/movie/tasproj/ZwinderStateManager.cs, src/BizHawk.Common/CustomCollections.cs, src/BizHawk.Tests/Common/CustomCollections/CustomCollectionTests.cs
The data structure for the StateCache was the culprit here.  The datastructure meant calls to Invalidate got slow at large numbers, even if no frames are determined to need to be invalidated, (the RemoveWhere() is still costly), causing painting to be laggy.
Using a custom SortedInt<int> allows for quick removals as well as fast duplicate check + additions.
Maybe a better structure could be conceived down the road but this seems to address the primary performance bottlenecks
=> StateManager - increase performance when there are a lot of states, fixes issue #2428

src/BizHawk.Client.Common/DisplayManager/DisplaySurface.cs, src/BizHawk.Client.Common/DisplayManager/FilterManager.cs, src/BizHawk.Client.Common/DisplayManager/Filters/BaseFilter.cs, src/BizHawk.Client.Common/DisplayManager/Filters/Gui.cs, src/BizHawk.Client.Common/DisplayManager/Filters/Retro.cs, src/BizHawk.Client.Common/DisplayManager/Filters/Utils.cs, src/BizHawk.Client.Common/DisplayManager/RenderTargetFrugalizer.cs, src/BizHawk.Client.Common/DisplayManager/SwappableDisplaySurfaceSet.cs, src/BizHawk.Client.Common/DisplayManager/TextureFrugalizer.cs, src/BizHawk.Client.Common/Sound/Interfaces/IBufferedSoundProvider.cs, src/BizHawk.Client.Common/Sound/Interfaces/ISoundOutput.cs, src/BizHawk.Client.Common/Sound/Utilities/BufferedAsync.cs, src/BizHawk.Client.EmuHawk/DisplayManager/DisplayManager.cs, src/BizHawk.Client.EmuHawk/Sound/Output/DirectSoundSoundOutput.cs, src/BizHawk.Client.EmuHawk/Sound/Output/DummySoundOutput.cs, src/BizHawk.Client.EmuHawk/Sound/Output/OpenALSoundOutput.cs, src/BizHawk.Client.EmuHawk/Sound/Output/XAudio2SoundOutput.cs, src/BizHawk.Client.EmuHawk/Sound/Utilities/SoundOutputProvider.cs, src/BizHawk.Client.EmuHawk/config/DisplayConfig.cs, src/BizHawk.Client.EmuHawk/tools/Watch/RamWatch.cs
natt wanted to know why this code should be moved, and why EmuHawk needed to be common-ised when it's our only frontend. This PR's motivations are to have less code targeting Framework (see also #1801), and to reduce the amount of non-UI code in the EmuHawk project. It's also uncertain if we'll be able to keep one executable that runs both on Windows and on Linux via Mono; though should EmuHawk split, most files can be included in both Core- and Framework-targeting projects without any modification or preprocessor guarding.
=> Move some more stuff to Client.Common

src/BizHawk.Bizware.BizwareGL/OpenTKConfigurator.cs, src/BizHawk.Bizware.DirectX/IGL_SlimDX9.cs, src/BizHawk.Client.EmuHawk/GlobalWin.cs, src/BizHawk.Client.EmuHawk/GraphicsImplementations/IGL_TK.cs, src/BizHawk.Client.EmuHawk/Program.cs
Mupen is still able to load on my Win10 machine with the D3D display method selected.
=> Cleanup initialisation of GlobalWin.GL

src/BizHawk.BizInvoke/MemoryViewStream.cs, src/BizHawk.Client.Common/config/RewindConfig.cs, src/BizHawk.Client.Common/rewind/ZwinderBuffer.cs
A future commit may expose this functionality for use in ZWinderStateManager.
Should we expose this directly to the user, so the rewinder can be disk based?
=> Refactor ZWinderBuffer to allow use of arbitrary backing Streams

src/BizHawk.Client.EmuHawk/IMainFormForTools.cs, src/BizHawk.Client.EmuHawk/MainForm.cs, src/BizHawk.Client.EmuHawk/tools/TAStudio/TAStudio.ListView.cs
Painting inputs in the piano roll can cause gaps in the greenzone and desyncs in movies if done while frame advance is happening. This PR prevents frame advance from any source while inputs are being painted.
=> Fix for state gap when frame advancing and painting input

src/BizHawk.Client.Common/Api/Classes/GuiApi.cs, src/BizHawk.Client.Common/Api/DisplaySurfaceID.cs, src/BizHawk.Client.Common/Api/Interfaces/IGuiApi.cs, src/BizHawk.Client.Common/DisplayManager/Filters/Gui.cs, src/BizHawk.Client.Common/DisplayManager/IDisplayManagerForApi.cs, src/BizHawk.Client.Common/lua/CommonLibs/GuiLuaLibrary.cs, src/BizHawk.Client.EmuHawk/DisplayManager/DisplayManager.cs, src/BizHawk.Client.EmuHawk/tools/Lua/LuaConsole.cs, src/BizHawk.Client.EmuHawk/tools/Lua/Win32LuaLibraries.cs
As before, `gui.draw*` draw to the "emu" surface without needing `gui.DrawNew("emu")`. There's a new function `gui.use_surface` to replace `gui.DrawNew("native")`. `gui.DrawFinish` is a no-op. I seem to be the only one who cares about ApiHawk so I won't bother explaining that.
I've tested the first commit on Windows, but not the second. The third is purely cosmetic and can be dropped.
=> Refactor DisplaySurface locking as used by ApiHawk (and Lua)

src/BizHawk.Client.EmuHawk/AVOut/VideoWriterChooserForm.Designer.cs
Alternate sync syncs video frames to audio instead of stretching audio to fit video, so rename it to describe that.
closes #1398
=> Rename Alternate Sync

src/BizHawk.Emulation.Cores/Consoles/Nintendo/SNES/LibsnesCore.IStatable.cs
The crash @g0me3 sent me was very simple to debug:  `cdlInfo.blocks` contains absolute garbage.  It appears that these are foreign pointers brought into the core, in which case they must be refangled on every state load.
=> Probably fix SNES core crash on load with CDL enabled, or formerly enabled

src/BizHawk.Client.Common/rewind/IRewinder.cs, src/BizHawk.Client.Common/rewind/Zwinder.cs, src/BizHawk.Client.EmuHawk/MainForm.cs
MainForm intentionally frame advances right after rewinding; this is so it can capture a new framebuffer.  The old rewinder sort-of understood this, the new one does not.  
Tweak the logic so the new rewinder behaves like the old one, but only when the interval is 1.  When the interval is greater than 1, don't go farther back than we have to.
No particular behavior is guaranteed when nonlinear time exists (ie, rewinding through manual loadstates).
Fixes #2667.
=> Tweak the rewinder.

src/BizHawk.Client.Common/savestates/ZipStateLoader.cs
- closes #2640 
SharpZipLib's `ZipEntry.Name` is actually equivalent to `ZipArchiveEntry.FullName`. `.Name` returns only the filename without directories.
*I really hope there aren't more of these subtle differences sprinkled across the code*
=> Fix #2640 due to library differences

src/BizHawk.Client.EmuHawk/CustomControls/InputRoll/InputRoll.cs, src/BizHawk.Client.EmuHawk/tools/TAStudio/BookmarksBranchesBox.cs
- rightclicking a branch when the contextmenu was already open would throw an exception and not work properly (I don't understand how 764f4ad81e744ce2b1949c6e97a46c0cb40debc8 tried to fix this very issue and somehow failed)
- branch view will now scroll to the updated branch when using hotkeys to update a branch as I feel like that makes sense
- fix #2645 (was broken in a2414f2b4ea41c18ad52b29e13f1a363b4ff425f)
=> Fix some TAStudio branch view issues

src/BizHawk.Client.Common/savestates/ZipStateLoader.cs
a91fa2754e21b0b2323bd06593ebcb57f24468e0 broke all old .tasproj files in that all branch info was not loaded from them. I don't think that is a wise choice? That's just asking for another #2640.
Some more info in hopes that it's helpful: all "old" tasproj files were saved with `\` as path separator, which was changed to `/` in the aforementioned commit. Without my fix here, the new logic will fail to understand `\` as path separator and ignore all branch etc. info in .tasproj files.
=> Support branches in all "old" .tasproj files

src/BizHawk.Client.Common/movie/tasproj/TasMovie.IO.cs
Before this would load old "incompatible" .tasprojs without any marker, making the first created marker take slot 1 and be uneditable and undeletable, seemingly without reason.
I have looked a bit into the discussion around this (#2023), but I think a quick fix is better for now.
Not sure if this line of code should be duplicated in the code as often as it is now (3 times total), so I'm open for suggestions on whether this could be handled better.
=> Add initial marker in frame 0 when loading older tasprojs

src/BizHawk.Emulation.Cores/Consoles/Nintendo/Gameboy/Gambatte.ISettable.cs
RTC covers both MBC3 and HuC3 games, not just MBC3 games. The correct term is "bootrom" rather than "BIOS", although "BIOS" is still mentioned here since that is more colloquial.
=> clarify Gambatte sync settings

src/BizHawk.Client.EmuHawk/tools/TAStudio/TAStudio.cs
- closes #2583
Note: while this works, I'm really unsure about the flow of loading a .bk2 versus loading a .tasproj file.
To me it seems like either I don't fully understand at which point what code is being run (and therefor `ConvertCurrentMovieToTasproj` having so little code makes sense) or
1. the `LoadFile` function below either does too much work, aka calls function that it doesn't need to
2. the `ConvertCurrentMovieToTasproj` is still missing some hard-to-notice features that the `LoadFile` function provides
either way the general loading code that is similar for both .bk2 and .tasproj files should probably be condensed so something like that can't happen.
=> Fix #2583 by adding a missing event handler

src/BizHawk.Client.EmuHawk/MainForm.Events.cs, src/BizHawk.Client.EmuHawk/config/FirmwaresConfig.Designer.cs, src/BizHawk.Client.EmuHawk/config/FirmwaresConfig.cs, src/BizHawk.Client.EmuHawk/config/PathConfig.cs
I don't think the link in `FirmwaresConfig` which opens `PathsConfig` is very helpful, and the link in `PathsConfig` which opens `FirmwaresConfig` is even less so. Removing them makes a few hacks redundant.
edit: force-pushed to remove both links instead of just one
=> Remove 2-way FirmwaresConfig<=>PathsConfig link

src/BizHawk.Emulation.Cores/Consoles/Sega/gpgx64/GPGXControlConverter.cs, src/BizHawk.Emulation.Cores/Consoles/Sega/gpgx64/LibGPGX.cs
See eafa39456f4a03395755b8ba69122655c843e9 and 307d85cee056298a6271f6537947296aeaa80a.
This will add extra keys that do nothing on certain non-menacer light guns, but that never seemed to bother anyone in 1.x.
Fixes #2717
=> Add missing menacer keys

src/BizHawk.Client.Common/tools/Interfaces/IToolForm.cs, src/BizHawk.Client.EmuHawk/tools/ToolFormBase.cs, src/BizHawk.Client.EmuHawk/tools/ToolManager.cs, src/BizHawk.Client.EmuHawk/tools/Watch/RamWatch.cs
replace some winforms specific values and ram watch chacks with IToolForm properties.  Removes hacks, and some winforms dependencies in tools, and allows for easier implementation of closeable tools
Note: this is a breaking change to existing external tools
=> Simplify IToolForm and remove winform specific notions

src/BizHawk.Client.EmuHawk/config/N64/N64VideoPluginconfig.Designer.cs, src/BizHawk.Emulation.Cores/Consoles/Nintendo/N64/N64SyncSettings.GLideN64.cs, src/BizHawk.Emulation.Cores/Consoles/Nintendo/N64/N64SyncSettings.Glide.cs, src/BizHawk.Emulation.Cores/Consoles/Nintendo/N64/N64SyncSettings.GlideMk2.cs, src/BizHawk.Emulation.Cores/Consoles/Nintendo/N64/N64SyncSettings.Rice.cs
Add `Category` attributes to N64 Plugin classes so that the `PropertyGrid` controls organizes them. Also disabled the maximize button for the N64 plugin form because the form is not resizable to begin with and maximizing the window breaks the `PropertyGrid` anchors.
- Does not add to the maintenance cost of updating the plugins any more than adding other attributes (`Name`, `Description`, etc) does.
- Forgetting to add a `Category` attribute does not break anything. The property will still show up just fine under a "Misc" category.
- For the most part, categories were taken from the organization of version 2.4.2 with only very cursory organizational changes.
- GLideN64 organization borrows from the mupen64 (zilmar-spec) plugin layout
- "Hacks" category for the per-game hacks override …
=> N64 plugin categories

src/BizHawk.Emulation.Cores/Consoles/Nintendo/Gameboy/Gambatte.IEmulator.cs, src/BizHawk.Emulation.Cores/Consoles/Nintendo/Gameboy/Gambatte.ISettable.cs, src/BizHawk.Emulation.Cores/Consoles/Nintendo/Gameboy/Gambatte.cs
Doesn't create a new core for sub-frame input, rather it just sets it as a sync setting. Gambatte is perfectly capable of doing sub-frame stuff already, all it needed was some frontend work.
=> [Gambatte] Add User-Defined Frame Length Type For Subframe TASing

src/BizHawk.Bizware.DirectX/DirectInputAdapter.cs, src/BizHawk.Bizware.DirectX/GamePad360.cs
Fixes #2782
Skips polling on disconnected Xinput controllers, wraps SetVibration call in a try/catch
=> Fix crash when XInput controllers disconnect

src/BizHawk.Client.Common/Api/MemoryMappedFiles.cs, src/BizHawk.Client.Common/lua/CommonLibs/CommLuaLibrary.cs, src/BizHawk.Client.EmuHawk/MainForm.cs
This commit adresses two things:
1. Currently, the MMF LUA functions are only available if Bizhawk is started with the "--mmf=filename" flag.
I think this is not intuitive, because we should not have to specify a filename in order to active MMF functions
as the given "filename" is only used for "mmfScreenshot" (and even for this function, the filename can be set in the LUA).
I changed this behavior so that MMF functions are always available, and "mmfScreenshot" will fail with a log if
no filename has been specified by the command line nor by the LUA script.
2. I have added several LUA functions:
- "mmfWriteBytes", "mmfReadBytes": to send/read a sequence of bytes to/from a memory mapped file
- "mmfCopyToMemory", "mmfCopyFromMemory": to copy the content of a memory mapped file to a given …
=> Always initialize MMF LUA functions + Add some MMF LUA functions

src/BizHawk.Client.Common/rewind/ZeldaWinder.cs, src/BizHawk.Client.Common/rewind/ZwinderBuffer.cs
When the deltastate rewinder needed to not capture a frame (interval > 1), it would get stuck and fail to capture any further frames.  Because the underlying zwinder buffer is one state behind in what it's storing, we need to adjust frame calc logic accordingly.
Closes https://github.com/TASVideos/BizHawk/issues/2866.
=> Fix bug with delta state rewinder

src/BizHawk.Emulation.Cores/Consoles/Nintendo/N64/N64SyncSettings.GLideN64.cs
Needs the updated version of GLideN64 that is commited to master to be useful first:
https://github.com/TASVideos/GLideN64/tree/Branch_bizhawk
That version will not work unless threaded video is turned off.
@vadosnaprimer Can you please update the .dll file of the repo with a working 2020-02 build of GLideN64?
These settings are added:
- BackgroundsMode: Sets the rendering mode of large background images, like the JFIF backgrounds of Ocarina of Time. Defaults to stripped as it is more accurate. A user may want to change this to one piece mainly for texture pack usage or performance.
- txEnhancedTextureFileStorage: Use HTS cache instead of HTC for enhanced (upscaled) textures. Defaults to HTC.
- txHiresTextureFileStorage: Use HTS cache instead of HTC for HD textures. Textures are streamed …
=> Add new GLideN64 settings

src/BizHawk.Client.EmuHawk/config/PathConfig.Designer.cs, src/BizHawk.Client.EmuHawk/config/PathConfig.cs
resolves #2435
With this changeset, the dialog looks like:
=> Redesign PathConfig

src/BizHawk.Client.Common/lua/LuaHelperLibs/EventsLuaLibrary.cs, src/BizHawk.Client.EmuHawk/tools/Lua/Win32LuaLibraries.cs
Adds a `string event.onclose(nluafunc luaf, [string name = nil])` event that fires every time the emulator closes.
=> Add onclose event

src/BizHawk.Emulation.Common/Database/FirmwareDatabase.cs
(`FirmwareAndOption` being the helper which declares a record *with a single option*.) These have always received the default of `Acceptable` since the status enum was introduced in f43859f42, with the exception of the FDS "Nintendo" BIOS (the first declaration, see b9e784e15). I believe that was unintentional.
This PR changes the *default* param value in `FirmwareAndOption`; individual calls may still override it with `Acceptable` if that is desired.
see also https://github.com/TASVideos/BizHawk/issues/2825#issuecomment-871231323 (icons for `Ideal` and `Acceptable` swapped?)
=> Set firmwares declared with `FirmwareAndOption` to `Ideal` status instead of `Acceptable`

src/BizHawk.Client.EmuHawk/tools/Lua/Libraries/FormsLuaLibrary.cs
Allows to disable automatic alphabetical sorting for the SetDropdownItems method by use of an optional "sort" parameter.
With this, it's possible to provide the form with a preordered list of options to allow for custom sorting algorithms, for example to force special characters to the end of the list, or to allow ordering by different metrics.
=> Add optional sort parameter to SetDropdownItems method

src/BizHawk.Client.Common/config/RewindConfig.cs, src/BizHawk.Client.Common/movie/tasproj/ZwinderStateManagerSettings.cs, src/BizHawk.Client.Common/rewind/ZwinderBuffer.cs, src/BizHawk.Client.EmuHawk/config/RewindConfig.Designer.cs, src/BizHawk.Client.EmuHawk/config/RewindConfig.cs
Fix #2463
No changes to TAStudio.
Outside of TAStudio, there's now an option to specify a fixed rewind interval instead of a desired frame length:
This is how the rewind frequency used to be specified in the pre 2.5 rewind system.
While the new way of specifying a "desired frame length" is great for TAStudio, it is very cumbersome outside of it: For one, with a buffer size of >20'000 frames, you need to specify a huge desired frame length of 100'000 to (approximately) get 5-frame rewinds.  And, more importantly, even if you set a desired frame length of 100'000, then the rewind intervals still vary (more or less randomly) between 4-6 frames, as the state size differs from frame to frame. This "randomness" makes them very awkward to use.
Don't get me wrong, TAStudio is an amazing tool for …
=> Add config option for rewinds every fixed number of frames.

src/BizHawk.Client.EmuHawk/tools/Watch/RamSearch.cs
fixes #2857 selecting the same combo box value in ram search should not reset the search
The issue was that a selected index changed event was always fired when an item was selected from the watch size dropdown, even if the selected setting was the same as the current setting. SetSize() was always called in this case, which would result in NewSearch() being called, even though the size was just being set to the same setting it was before.
This fix addresses the issue by separating out setting the size (SetSize()) from handling a size selection (HandleWatchSizeSelected()). In HandleWatchSizeSelected(), SetSize() will only be called if the size setting has actually changed. This also allows SetSize() to still be called directly to always perform a setting change. This allows for the …
=> Add HandleWatchSizeSelected() to allow user-initiated watch size changes to be ignored if they reset the setting to the same value

src/BizHawk.Client.Common/fwmanager/FirmwareManager.cs, src/BizHawk.Client.EmuHawk/MainForm.Debug.cs, src/BizHawk.Emulation.Common/Database/FirmwareDatabase.cs, src/BizHawk.Emulation.Common/Database/FirmwarePatchData.cs, src/BizHawk.Emulation.Common/Database/FirmwarePatchOption.cs, src/BizHawk.Emulation.Cores/Consoles/Nintendo/Gameboy/Gambatte.ISettable.cs, src/BizHawk.Emulation.Cores/Consoles/Nintendo/Gameboy/Gambatte.cs
Replaces hack in Hawk-side Gambatte. (I recall seeing other hacks, but can't find any.) Would also work for NDS if the hashes of all N permutations were hardcoded... I have ideas for how to get around that limitation.
I also added a simple tool to `Help` > `Debug Utilities` for trying out this feature without needing to mess around with firmware customisations and sync settings.
edit 2021-09-18: Force-pushed because of #2917. The extra two patchsets added in that PR (which happen to be identical to existing ones) are now included here. I also realised it was stupid to hardcode the reverse of a patchset instead of computing it, so that's gone.
=> Add automagic patching capability to `FirmwareManager`

src/BizHawk.Emulation.Cores/Consoles/Nintendo/NES/Boards/SxROM.cs, src/BizHawk.Emulation.Cores/Consoles/Nintendo/NES/NES.iNES.cs
fixes #3168. 
Skeptical about these changes as I also discovered iNES 2.0 detection ended up producing 4 digits for the board number instead of 3 like iNES 1.0 does. I assume 3 digits is the intended width (otherwise iNES 2.0 seems to just be useless?). Not sure if this is correct however. EDIT: Might be related to https://github.com/TASEmulators/BizHawk/issues/3082#issuecomment-1017690152
=> Fix SXROM Detection

src/BizHawk.Client.Common/tools/Watch/ByteWatch.cs, src/BizHawk.Client.Common/tools/Watch/DWordWatch.cs, src/BizHawk.Client.Common/tools/Watch/WordWatch.cs, src/BizHawk.Client.EmuHawk/tools/Watch/WatchValueBox.cs, src/BizHawk.Common/Extensions/NumericStringExtensions.cs
closes #3175
float and fixed-point numbers are basically handled the same right now, whereas previously float was the only type that was allowed a `-` sign (should be correct now).
In general, this code that is supposed to do text validation and value checking seems to be massively overengineered, otherwise such issues wouldn't even come up (a simple float.TryParse or whatever should catch everything that isn't valid and return sane values in all cases).
Anyway, I was too scared to do any major logic changes so this is what we get now.
=> Allow negative values to be entered in ram watch for fixed-point watches

src/BizHawk.Client.Common/DisplayManager/Filters/Retro.cs
previously, a height specified absolutely would affect the output width instead of the height.
=> fix absolute dimensions of shaders

src/BizHawk.Client.Common/lua/CommonLibs/ClientLuaLibrary.cs, src/BizHawk.Client.Common/lua/CommonLibs/CommLuaLibrary.cs, src/BizHawk.Client.Common/lua/CommonLibs/EmulationLuaLibrary.cs, src/BizHawk.Client.Common/lua/CommonLibs/GameInfoLuaLibrary.cs, src/BizHawk.Client.Common/lua/CommonLibs/GuiLuaLibrary.cs, src/BizHawk.Client.Common/lua/CommonLibs/InputLuaLibrary.cs, src/BizHawk.Client.Common/lua/CommonLibs/JoypadLuaLibrary.cs, src/BizHawk.Client.Common/lua/CommonLibs/MemoryLuaLibrary.cs, src/BizHawk.Client.Common/lua/CommonLibs/MemorySavestateLuaLibrary.cs, src/BizHawk.Client.Common/lua/CommonLibs/MovieLuaLibrary.cs, src/BizHawk.Client.Common/lua/CommonLibs/SQLiteLuaLibrary.cs, src/BizHawk.Client.Common/lua/CommonLibs/SaveStateLuaLibrary.cs, src/BizHawk.Client.Common/lua/CommonLibs/UserDataLuaLibrary.cs, src/BizHawk.Client.Common/lua/IPlatformLuaLibEnv.cs, src/BizHawk.Client.Common/lua/LuaAttributes.cs, src/BizHawk.Client.Common/lua/LuaHelperLibs/EventsLuaLibrary.cs, src/BizHawk.Client.Common/lua/LuaHelperLibs/MainMemoryLuaLibrary.cs, src/BizHawk.Client.Common/lua/LuaHelperLibs/NDSLuaLibrary.cs, src/BizHawk.Client.Common/lua/LuaHelperLibs/StringLuaLibrary.cs, src/BizHawk.Client.Common/lua/LuaLibraryBase.cs, src/BizHawk.Client.EmuHawk/tools/Lua/Libraries/ConsoleLuaLibrary.cs, src/BizHawk.Client.EmuHawk/tools/Lua/Libraries/FormsLuaLibrary.cs, src/BizHawk.Client.EmuHawk/tools/Lua/Libraries/TAStudioLuaLibrary.cs, src/BizHawk.Client.EmuHawk/tools/Lua/LuaCanvas.cs, src/BizHawk.Client.EmuHawk/tools/Lua/UnixLuaLibraries.cs, src/BizHawk.Client.EmuHawk/tools/Lua/Win32LuaLibraries.cs, src/BizHawk.Common/Extensions/StringExtensions.cs
Example script that would print garbage without this changeset:
```lua
local s = "こんにちは、世界さん！";
console.writeline(s);
while true do
gui.drawText(15, 110, s, "goldenrod", "darkblue", 12, "Microsoft YaHei"); -- or "Noto Sans CJK JP" on Linux
emu.yield();
end
```
But now it prints (except on Linux, where the Lua Console displays tofu) and draws this on the screen (if the necessary font is installed and specified):
I've done my best to make sure every method converts to and/or from UTF-8 if the argument/return strings could possibly contain non-ASCII text. If a function returns nested tables then I didn't bother. All the `string`s (plus `object`s and `LuaTable`s) in method signatures have one of 3 new attributes, and there's also a warning in stdout if a `string` param/return is unannotated. …
=> Fix Lua string encoding bug

src/BizHawk.Client.EmuHawk/MainForm.Events.cs, src/BizHawk.Client.EmuHawk/config/GenericCoreConfig.cs, src/BizHawk.Emulation.Cores/Consoles/NEC/PCE/HyperNyma.cs, src/BizHawk.Emulation.Cores/Consoles/NEC/PCE/TurboNyma.cs, src/BizHawk.Emulation.Cores/Consoles/NEC/PCFX/Tst.cs, src/BizHawk.Emulation.Cores/Consoles/Nintendo/Faust/Faust.cs, src/BizHawk.Emulation.Cores/Consoles/Nintendo/VB/VirtualBoyee.cs, src/BizHawk.Emulation.Cores/Consoles/SNK/NeoGeoPort.cs, src/BizHawk.Emulation.Cores/Consoles/Sega/Saturn/Saturnus.cs, src/BizHawk.Emulation.Cores/Consoles/Sony/PSX/Nymashock.cs, src/BizHawk.Emulation.Cores/Waterbox/NymaCore.Settings.cs, src/BizHawk.Emulation.Cores/Waterbox/NymaCore.cs
The details are icky here. Info on the settings is stored in the unmanaged core. So no matter what a core instance is needed at some point.
Now settings info here should be constant for a given core, so we can cache settings info after the core has been loaded and use that.
If in the case the user wants to edit the settings but the core has never been loaded, a minimal load will be done to obtain the settings (and cache them) and quickly dispose thereafter.
This code could probably be cleaner, but not sure how to do so.
=> Support editing nyma settings without the core loaded

src/BizHawk.Client.EmuHawk/tools/BasicBot/BasicBot.Designer.cs
Some games, such as River City Ransom EX for the GBA, has an RNG counter period 0x270 to 0x1, which has an average of around 1200 frames to be able to see potential RNG routes to take. "999" is too small for this. I also don't see any issues with increasing the max limit from 999 to 9999.
=> Increased Basic Bot max frames from 999 to 9999.

src/BizHawk.Client.Common/movie/MovieConversionExtensions.cs, src/BizHawk.Client.Common/movie/bk2/Bk2Movie.InputLog.cs, src/BizHawk.Client.Common/movie/interfaces/IMovie.cs
See: #2843, #2567.
Before, loading a bk2 with a specific `KeyLog` set in TAStudio would just discard it, effectively mis-matching all inputs.
It was possible to craft a .tasproj with a different `KeyLog` by manually editing the `InputLog` file, but on saving the same issue would occur.
I have fixed the `KeyLog` getting discarded in the cases of bk2 -> tasproj, tasproj -> bk2 and saving a tasproj in general.
Here are two files (one .bk2, one .tasproj) that should show the difference in the `InputLog` and what is displayed in TAStudio when loading them:
[Movies.zip](https://github.com/TASEmulators/BizHawk/files/8904678/Movies.zip)
I have tested this and I believe this to work fine, however I would like to get some feedback on whether I may have missed something (or there is a better way of …
=> Fix KeyLog not being respected in TAStudio

src/BizHawk.Client.EmuHawk/tools/BasicBot/BasicBot.Designer.cs, src/BizHawk.Client.EmuHawk/tools/BasicBot/BasicBot.cs
Gave the Basic Bot a NOT operator.
This is useful for cases where we are checking for volatile RAM address values, and we don't want it to be specific to a certain value.
=> Added NOT operator to Basic Bot.

src/BizHawk.Client.EmuHawk/tools/BasicBot/BasicBot.Designer.cs
I added the NOT operator to the Basic Bot, but it was only for the Main Value. This PR aims to fix it so all the Tie-Breakers have the NOT operators.
=> Added missing NOT operators from the dropdown menu.

src/BizHawk.Client.EmuHawk/tools/BasicBot/BasicBot.Designer.cs
Fixed UI:
* When Basic Bot window is maximized, the UI panels are now properly aligned to take up space.
* Fixed a label, "Main Value:", being misaligned slightly towards the text box, making the label stand out among the other labels below it. The label is located on the right-most side of the window.
[//]: # "Apart from the mandatory license signature, these tasks are optional, but doing them could …
=> Fixed Basic Bot anchor points and one label misalignment

src/BizHawk.Client.EmuHawk/tools/BasicBot/BasicBot.cs
It was comparing with itself when it's comparing the Tie Breaker 3 value.
=> Fixed code logic error in BasicBot

src/BizHawk.Client.EmuHawk/tools/BasicBot/BasicBot.cs
If the Copy button is enabled, but there is no best attempt recorded, it will crash BasicBot / EmuHawk if it attempts to copy a null Log of the best attempt.
=> Fixed issue where the Copy button in Basic Bot is not toggled on/off properly.

src/BizHawk.Client.Common/input/InputCoalescerControllers.cs, src/BizHawk.Client.EmuHawk/Input/Input.cs
This would close #3327. As I've written in that issue thread, the main problem seems to be the fact that key release events were sent with their respective modifier, aka when holding e.g. `Ctrl+C` and releasing `C`, a `Release:Ctrl+C` event would be generated which also happned to release the `Ctrl` key, even though that was still pressed.
The comments and code which I've removed seem to imply that this functionality was (more or less) intended and had a use case, although in my testing I couldn't figure out an issue with removing it; @zeromus do you recall the specific reason this code was needed?
=> Don't send key release events with modifiers

src/BizHawk.Client.Common/config/Config.cs, src/BizHawk.Client.EmuHawk/tools/Lua/LuaConsole.cs, src/BizHawk.Client.EmuHawk/tools/Lua/LuaRegisteredFunctionsList.cs
This PR fixes a number of issues in `LuaConsole`, mostly related to script loading/unloading
1. Change references to `Config.DisableLuaScriptsOnLoad` to `Settings.DisableLuaScriptsOnLoad`
This was inconsistently done in an old commit, leading to some functions obeying this setting and others ignoring it.
This will effectively reset the setting
2. `Close()` existing `Win32LuaLibraries` during `Restart()`.
Before, only closing the `LuaConsole` would call close on the current `LuaImp`, causing possible memory and file handle leaks, and leaving behind 'zombie' forms still referencing the old libraries after loading a rom/restarting the core
3. Dispose `FileSystemWatcher` when no longer needed, avoid relying on path string comparisons, prevent crash in case of missing directory, and prevent …
=> LuaConsole fixes

src/BizHawk.Client.Common/DisplayManager/DisplaySurface.cs
- Replace `DisplaySurface.Clear()` with a significantly faster implementation
- Remove unused `int[]` pixel buffer and superfluous conversion between the array and `Bitmap`
My aim was to improve the performance of drawing on the "client" surface from Lua, which I've always avoided using simply because it causes huge FPS drops compared to drawing on "emucore" regardless of how simple the drawing is, especially at larger window sizes.
Much of the performance drain comes from `DisplaySurface.Clear()`, which uses a fairly slow byte-for-byte loop to clear the `_pixels` array. And then the cleared `_pixels` data is later copied back to the `Bitmap`.
With this PR, `DisplaySurface.Clear()` now clears the `Bitmap` directly (`LockBits`), and uses `Span<byte>.Clear()` which is a lot faster than the …
=> Improve `DisplaySurface` performance

src/BizHawk.Client.EmuHawk/tools/HexEditor/HexEditor.cs
- Replace `OpenAdvanced_MAME` check with `_romDomain` `null` check
Fix `NullReferenceException` when changing memory domains on MAME, now that MAME roms can be opened without using the Open Advanced dialog (related to bae71326bf21a392cb360db807214d4132ecb288) 
- Clear `_romDomain` reference when loading MAME rom
Previously, when loading a MAME rom after a non-MAME rom, the "File on Disk" domain would still appear with the contents of the previous rom
For context: `_romDomain` is the "File on Disk" pseudo memory domain in the hex editor, which is not initialized for MAME roms.
=> Fix hex editor domain issues with MAME

src/BizHawk.Client.Common/ArgParser.cs, src/BizHawk.Client.Common/ParsedCLIFlags.cs, src/BizHawk.Client.EmuHawk/MainForm.cs
As an example, `./EmuHawkMono.sh '--userdata=a:1;b:.5;c:1b;d:00;e:true;f:TRUE'` (quoted because ';' is a special char in BASH) sets these userdata entries:
key | type | value
--:|:--|:--
`a` | int | `1`
`b` | double | `0.5`
`c` | string | `"1b"`
`d` | int | `0`
`e` | bool | `true`
`f` | string | `"TRUE"`
=> Add `--userdata` CLI flag

Assets/changelog.md
Not sure if the following commits need to be mentioned, because most of them either solve issues not present in 2.8 or change things that only affect the devs:
[1ca610b42 YoshiRulz] Set default `Form.Icon` to corphawk
not sure about this, and I think it also affects ext. tools
[e8dd2e94f CasualPokePlayer] Fix crashes when using menu item for save/load quicksave
fixes 22ba0d5c25288defc39254f62e9885043d8edcd3
[cd1d647d7 CasualPokePlayer] linux build for recent gambatte updates, also fix a minor potential build error when zlib is completely unavailable (it was getting linked even though there was no need for it to be linked)
[bc823f479 YoshiRulz] Clear props of type `ApiContainer` when clearing injected API props
[3c00c24fc YoshiRulz] Fix `ApiInjector` trying to set get-only props of type …
=> changelog update

src/BizHawk.Emulation.Common/Base Implementations/MemoryCallbackSystem.cs, src/BizHawk.Tests/Emulation.Common/Base Implementations/MemoryCallbackSystemTests.cs
- Implement a specialized collection for `IMemoryCallback` used in `MemoryCallbackSystem` with copy-on-write behavior to safely handle adding/removing callbacks from within a callback.
- Add some basic tests for `MemoryCallbackSystem`
635fff6c5d574b161129d52a61ccead2e8897b0d addressed #1823, but the logic is still not quite correct: when a callback is removed, it will skip whatever callback is last in the list rather than the one that was removed. It also causes a significant performance hit on something that can run countless times per frame, due to the allocations and (un)subscribing `CollectionChanged` (which can be surprisingly expensive on multicast delegates).
This PR replaces the use of `ObservableCollection<T>` with a custom, pared down collection that only handles the needs of …
=> Improve performance and correctness of memory callbacks

src/BizHawk.Emulation.Cores/Consoles/Nintendo/NES/NES.Core.cs
This will correct open bus execution following write instructions.
Here's an example: 
Address $0056 has a value of $CC. Before this fix, an LSR instruction would leave $CC on the open bus:
However, when the LSR instruction writes the result to memory, the new result will be on the bus. Here's the result with the changes I made:
This corrected behavior is also demonstrated on Visual6502:
This issue was …
=> Nes.Core now updates the DataBus in WriteMemory()

src/BizHawk.Client.Common/movie/BasicMovieInfo.cs, src/BizHawk.Client.Common/movie/MovieSession.cs, src/BizHawk.Client.Common/movie/bk2/Bk2Movie.HeaderApi.cs, src/BizHawk.Client.Common/movie/bk2/Bk2Movie.IO.cs, src/BizHawk.Client.Common/movie/bk2/Bk2Movie.cs, src/BizHawk.Client.Common/movie/interfaces/IBasicMovieInfo.cs, src/BizHawk.Client.Common/movie/interfaces/IMovie.cs, src/BizHawk.Client.Common/movie/tasproj/TasMovie.IO.cs, src/BizHawk.Client.EmuHawk/movie/PlayMovie.cs, src/BizHawk.Client.EmuHawk/tools/TAStudio/HeaderEditor.cs
This is an RFC.
This change allows parsing basic movie fields into an own class that is independent from Bk2Movie/TasMovie.
The current Hierarchy is `IBasicMovieInfo` <- `IMovie` (<- `ITasMovie`).
The current separation of fields between `IMovie` and `IBasicMovieInfo` is mainly driven by what fields seem useful outside of a movie context and which don't, but I'm open for change requests.
This is mainly useful for the PlayMovie dialog which can now load movie information from files on disk without having to go through the entire Bk2Movie/TasMovie loading process.
The main purpose of this change is to allow the `PlayMovie` dialog to operate quickly and without churning memory. This should also resolve all reported issues about VirtualAlloc returning NULL.
Some additional changes I've done: …
=> Implement IBasicMovieInfo interface for IMovie

src/BizHawk.Client.EmuHawk/tools/TAStudio/PatternsForm.cs
This changeset addresses two issues with TAStudio/PatternsForm:
- Fixes bug introduced by 883d74d preventing the user from changing the destination of the loop to entry 0
- Fixes #3368 by adding the recommended special case
=> Fix bugs with entries in patternsform

src/BizHawk.Emulation.Cores/Sound/SN76489sms.cs
On the SMS/GG VDP, the noise channel of the integrated SN76489 is a 16-bit LFSR instead of a 15-bit one, this PR should fix that. Also, white noise is generated by XORing bits 0 and 3, not 0 and 1.
Finally, reverting commit 7b857e7 nonsense.
Check if …
=> fix noise audio channel on SMS VDP (LFSR is 16 bit wide)

src/BizHawk.Client.Common/movie/MovieSession.cs, src/BizHawk.Client.Common/movie/bk2/Bk2Movie.cs, src/BizHawk.Client.EmuHawk/tools/TAStudio/BookmarksBranchesBox.cs
Resolves #3741.
Previously loading a state would either not update the input display (in case of TAStudio) or make the input display display the current frame's inputs, not the inputs of the previous frame (outside of TAStudio).
I'm honestly unsure if this can break anything so I'm making a PR instead of pushing to master directly.
=> Set inputdisplay correctly on LoadState

src/BizHawk.Emulation.Cores/Waterbox/NymaCore.cs
Override `Dispose` in `NymaCore` and dispose opened disks like other cores do. Affects Nymashock, Saturnus and possibly others
This should resolve #3750 
=> Dispose disks in Nyma cores

src/MainSlnExecutable.props
This PR modifies the build target that moves files into the `dll` subdirectory to exclude the PDBs for `EmuHawk.exe` and `DiscoHawk.exe`.
This allows VS to find those PDBs automatically, which improves the debugger experience when profiling or debugging release builds, without having to manually load those PDBs or fiddle with the symbol source locations.
=> Stop moving exe PDBs to dll folder

src/BizHawk.Client.EmuHawk/tools/Watch/RamWatch.Designer.cs, src/BizHawk.Client.EmuHawk/tools/Watch/RamWatch.cs
- Add a new setting to the `RamWatch` dialog menu that changes whether double-clicking a watch in the list will open the Edit or the Poke dialog. 
- Setting defaults to poke (previous behavior was edit)
- Pressing enter also obeys this setting 
Resolves #3688
=> Add setting to control what happens when double-clicking RAM watch 

contributing.md
=> fix typo in contributing.md

.github/pull_request_template.md, contributing.md
* make the GitHub Copilot note more prominent
[Rendered](https://github.com/RetroEdit/BizHawk/blob/contributor-agreement-change/contributing.md#copyrights-and-licensing)
I thought the phrasing for the contributor's licensing agreement could be improved, since it was created since the last time I contributed and I didn't review it at that point in time.
=> update PR license agreement to clarify licensing

src/BizHawk.Client.EmuHawk/MainForm.Designer.cs, src/BizHawk.Client.EmuHawk/MainForm.Events.cs, src/BizHawk.Client.EmuHawk/MainForm.cs
Fixes #3826 
`View` -> `Window Size` can now be set to factors of x1-x10, instead of x1-x5 & x10.
=> Add some larger sizes to `View` -> `Window Size` (Fixes #3826)

src/BizHawk.Client.EmuHawk/CustomControls/InputRoll/Cell.cs, src/BizHawk.Client.EmuHawk/CustomControls/InputRoll/InputRoll.cs, src/BizHawk.Client.EmuHawk/tools/TAStudio/TAStudio.MenuItems.cs, src/BizHawk.Common/CustomCollections.cs
Following up on https://github.com/TASEmulators/BizHawk/commit/6d40c08c3c1404a217617c0bd237ba58f1ada76c#r139706953. Turns out I'd [already had that idea](https://github.com/TASEmulators/BizHawk/commit/67ba0e4f238a323a90a94dd3d25f7e9a08331830) some years ago (time flies) but never finished it.
I've tested this by trying a few of TAStudio's features and the assertion was never hit, but it deserves more scrutiny, and the `RemoveAll` call that was the impetus for all this will need reprofiling.
=> Replace `SortedSet` with `SortedList<T>` in `InputRoll`

default.nix, shell.nix
The only things keeping both `default.nix` and `shell.nix` from evaluating in [pure evaluation mode](https://nixos.org/manual/nix/stable/command-ref/conf-file#conf-pure-eval) are the lack of checksums on calls to `builtins.fetchTarball`, and the lack of a `system` attribute to be passed down to their corresponding `import` statements. The associated URLs have not been changed in 5 months and thus don't …
=> make default.nix and shell.nix pure by adding checksums and system

waterbox/bsnescore/Makefile
bsnes build broke when rewind.c was removed because it defined the GB_rewind_reset, which was being linked in despite being no longer present. -DGB_DISABLE_REWIND turns off this link
=> Fixed bsnes build

src/BizHawk.Client.EmuHawk/config/AmstradCPC/AmstradCPCNonSyncSettings.Designer.cs
Updated Amstrad CPC Non-Sync Settings text to be more accurate.
This was done by changing the label in the AmstradCPCNonSyncSettings.Designer.cs file
This solves issue #3845
=> Updated Amstrad CPC Non-Sync Settings name

src/BizHawk.Client.EmuHawk/tools/NES/NESPPU.Designer.cs
Expanded the palette viewer to show all the palettes.
For some reason, this object was only 192 pixels wide, instead of 256. The fourth palette is getting cut off:
By making this change, all the palettes are visible:
=> Expanded color palette object inside Nes PPU Viewer

src/BizHawk.Client.EmuHawk/MainForm.cs
Move the update of `MainForm.CurrentlyOpenRom` and `CurrentlyOpenRomArgs` to happen before calling `Tools.Restart`. 
Before this PR, tools that read those properties inside `Restart` still see the path to the previous rom when switching games (or no path if no rom was loaded before), causing various bugs with internal tools listed in #3527.
=> Update `CurrentlyOpenRom` before `Tools.Restart`

src/BizHawk.Emulation.Cores/Consoles/Sega/gpgx64/GPGX.IDebuggable.cs
Fixing a bug reported by Morilli where GPGX crashes upon trying to load a state on SMS's Galactic Protector:
```
System.NotImplementedException: The method or operation is not implemented.
at BizHawk.Emulation.Cores.Consoles.Sega.gpgx.GPGX.get_MemoryCallbacks () [0x00019] in <655556b5f7fe4f2daa09dea9e80ee688>:0 
at BizHawk.Emulation.Cores.Consoles.Sega.gpgx.GPGX.RefreshMemCallbacks () [0x00000] in <655556b5f7fe4f2daa09dea9e80ee688>:0 
```
=> [Core: GPGX] Fixing a wrong variable name that caused a crash in GPGX's load state

src/BizHawk.Client.EmuHawk/CustomControls/InputRoll/Cell.cs, src/BizHawk.Client.EmuHawk/CustomControls/InputRoll/ColumnType.cs, src/BizHawk.Client.EmuHawk/CustomControls/InputRoll/InputRoll.Drawing.cs, src/BizHawk.Client.EmuHawk/CustomControls/InputRoll/InputRoll.cs, src/BizHawk.Client.EmuHawk/CustomControls/InputRoll/RollColumn.cs, src/BizHawk.Client.EmuHawk/CustomControls/InputRoll/RollColumns.cs, src/BizHawk.Client.EmuHawk/tools/Cheats/Cheats.cs, src/BizHawk.Client.EmuHawk/tools/Lua/LuaConsole.cs, src/BizHawk.Client.EmuHawk/tools/TAStudio/BookmarksBranchesBox.cs, src/BizHawk.Client.EmuHawk/tools/TAStudio/TAStudio.ListView.cs, src/BizHawk.Client.EmuHawk/tools/Watch/RamSearch.cs, src/BizHawk.Client.EmuHawk/tools/Watch/RamWatch.cs
Starting on https://github.com/TASEmulators/BizHawk/pull/3869#issuecomment-1999636215. This builds upon that PR and the subsequent commits through to https://github.com/TASEmulators/BizHawk/commit/d67b1c1d237b151e6be8fa9dcaf2247768253f33, mainly https://github.com/TASEmulators/BizHawk/commit/4f144c74d47021018bc3252393db8685d98d58c7.
=> Enable nullability for `Cell` and co. and clean up

src/BizHawk.Client.EmuHawk/CustomControls/ClipboardEventTextBox.cs, src/BizHawk.Client.EmuHawk/CustomControls/HexTextBox.cs, src/BizHawk.Client.EmuHawk/tools/Watch/WatchValueBox.cs, src/BizHawk.Common/Extensions/NumericStringExtensions.cs, src/BizHawk.Tests/Common/StringExtensions/NumericStringExtensionTests.cs
- Add `ClipboardEventTextBox` control with an `OnPaste` method and make  `HexTextBox` and `WatchValueBox` inherit from that
- Override normal paste behavior to trim `0x`/`$`/whitespace from pasted text
- Prevent pasting of non-hex text
Resolves  #3682
=> Sanitize text pasted into hex text boxes

src/BizHawk.Emulation.Common/Database/FirmwareDatabase.cs
Renaming Firmware Files based on System Name as BizHawk uses or at least renamed to be related to what it's for.
This changes the Auto-Renamed Firmware Files to be named based on the System ID.
Or to be more Descriptive.  So the users can see helpful file names.
The File has been formatted to use LF instead of CRLF.  Which is why it feels like a "Full Replacement"
Examples of Old Name:
cx4.rom
KoF95.bin …
=> Better Firmware Names

src/BizHawk.Client.EmuHawk/tools/Macros/MacroInput.cs, src/BizHawk.Client.EmuHawk/tools/TAStudio/TAStudio.IToolForm.cs, src/BizHawk.Client.EmuHawk/tools/ToolManager.cs
- ~~Bail out of `TAStudio.AskSaveChanges()` if dialog is already disposed~~
- Stop calling `AskSaveChanges()` on inactive tools
- Fix #3499
=> Fix possible TAStudio NRE

src/BizHawk.Client.EmuHawk/IMainFormForTools.cs, src/BizHawk.Client.EmuHawk/MainForm.Movie.cs, src/BizHawk.Client.EmuHawk/MainForm.cs, src/BizHawk.Client.EmuHawk/tools/TAStudio/TAStudio.IControlMainForm.cs, src/BizHawk.Client.EmuHawk/tools/TAStudio/TAStudio.cs, src/BizHawk.Client.EmuHawk/tools/ToolManager.cs
- closes #3870
This changes the handling of `IControlMainform` tools loaded in the following way:
There is no longer a way for a tool to take or relinquish control over all mainform actions specified in that interface, instead, each of the `WantsToControlX` fields are queried for all loaded tools, and if one matches, that tool will be controlling this action.
That means that there could now be different loaded tools handling different actions, for example one tool controlling rewind, a different tool controlling savestates, etc.
Additionally, `CreateRewinder` now returns immediately if any tool has `WantsToControlRewind` set to true, for example TAStudio.
This still feels a bit arbitrary, every tool wanting to control rewind will have to manually disable rewind on load and re-enable it on …
=> Refactor IControlMainform handling in Mainform

src/BizHawk.Emulation.DiscSystem/DiscFormats/CUE/CueFileResolver.cs
Partially revert 7cde8bb466c34c3c9fae213c196a0a0602a60aab. Original code split the path into both filename and filename without extension, to match files with a different file extension as well as files with an added file extension (`foo.bin` -> `foo.bin.ecm`). 7cde8bb accidentally changed it so `targetFile` contains the directory part (probably `""`) instead of the file name with extension.
=> Fix fuzzy cue file resolving

src/BizHawk.Client.Common/config/PathEntryCollectionExtensions.cs, src/BizHawk.Client.EmuHawk/tools/ExternalToolManager.cs
Fixes default external tools directory not being found if BizHawk is launched with a working directory other than the exe directory.
=> Make external tools path independent of working directory

src/BizHawk.Client.EmuHawk/tools/HexEditor/HexEditor.cs
Changes to loading the rom file for the "File on Disk" memory domain.
- Fix "File on Disk" domain not staying selected after core restart
- Fix NRE when file is missing
- Catch other errors (e.g. file in use) so hex editor can still be opened
- Little bit of code cleanup
=> HexEditor "File on Disk" fixes

src/BizHawk.Client.EmuHawk/MainForm.cs, src/BizHawk.Emulation.Common/Interfaces/Services/IDriveLight.cs, src/BizHawk.Emulation.Cores/Calculators/Emu83/Emu83.IDriveLight.cs, src/BizHawk.Emulation.Cores/Computers/AmstradCPC/AmstradCPC.cs, src/BizHawk.Emulation.Cores/Computers/AppleII/AppleII.cs, src/BizHawk.Emulation.Cores/Computers/Commodore64/C64.IDriveLight.cs, src/BizHawk.Emulation.Cores/Computers/Commodore64/Cartridge/CartridgeDevice.cs, src/BizHawk.Emulation.Cores/Computers/Commodore64/Cartridge/CartridgePort.cs, src/BizHawk.Emulation.Cores/Computers/Commodore64/Serial/SerialPort.cs, src/BizHawk.Emulation.Cores/Computers/SinclairSpectrum/ZXSpectrum.cs, src/BizHawk.Emulation.Cores/Consoles/Atari/jaguar/VirtualJaguar.cs, src/BizHawk.Emulation.Cores/Consoles/Fairchild/ChannelF/ChannelF.cs, src/BizHawk.Emulation.Cores/Consoles/Nintendo/NES/NES.IDriveLight.cs, src/BizHawk.Emulation.Cores/Consoles/PC Engine/PCEngine.IDriveLight.cs, src/BizHawk.Emulation.Cores/Consoles/Sega/PicoDrive/PicoDrive.cs, src/BizHawk.Emulation.Cores/Consoles/Sega/gpgx64/GPGX.IDriveLight.cs, src/BizHawk.Emulation.Cores/Consoles/Sony/PSX/Octoshock.cs, src/BizHawk.Emulation.Cores/Waterbox/NymaCore.Cd.cs
A number of cores are using the IDriveLight interface, but many of them aren't using it for disk drive activity. We have disks, CDs, carts and other things hooked up.
This PR adds a DriveLightIconDescription string to the IDriveLight interface, allowing for cores to set their own ToolTip on the drive light icon.
I was planning on using a default implementation in the interface (so that cores didn't have to explicitly set a value and we could use the default), but it looks like this might require a higher version of C#.
Thoughts?
=> Disk Drive Activity LED ToolTip enhancement

Directory.Packages.props, Dist/deps.nix, README.md, src/BizHawk.Client.Common/ArgParser.cs, src/BizHawk.Client.Common/BizHawk.Client.Common.csproj, src/BizHawk.Client.EmuHawk/Program.cs
~~I'd still like to improve the documentation further, but this is functional already.~~ Documentation improved. If you have scripts for e.g. encoding please test them.
Don't merge without checking the commit hash in `README.md` (it should be of the commit immediately before the readme change).
=> `ArgParser` rewrite

src/BizHawk.Emulation.DiscSystem/DiscoHawkLogic/DiscoHawkLogic.cs
Add `using` statement to stop DiscoHawk from holding on to file handles.
=> Dispose input files in DiscoHawk

src/BizHawk.Client.Common/Api/Classes/EmuClientApi.cs, src/BizHawk.Client.Common/IMainFormForApi.cs, src/BizHawk.Client.Common/config/Config.cs, src/BizHawk.Client.EmuHawk/IMainFormForTools.cs, src/BizHawk.Client.EmuHawk/MainForm.Designer.cs, src/BizHawk.Client.EmuHawk/MainForm.Events.cs, src/BizHawk.Client.EmuHawk/MainForm.cs, src/BizHawk.Tests/Client.Common/config/SerializationStabilityTests.cs
- Add option to disable the automatic resizing of the main window whenever the framebuffer size changes
- Window can be resized arbitrarily and stays that size
- Selecting a standard scale through the menu/keybinds/API still works
- Restore last window size after restart (if automatic resize is disabled)
- Minor changes to saved window position
- Make config values nullable instead of magic `-1` value
- Don't save window position if minimized (this didn't quite work as intended) or maximized
This feature is useful for streamers who want a consistent capture size, as well as for people who want to fit the BizHawk window into a fixed layout with other windows (corner snapping etc.).
This is not the same functionality as the custom resolution in the display settings, which stretches the …
=> Add option to disable automatic resize of main window

src/BizHawk.Client.Common/config/Config.cs, src/BizHawk.Client.EmuHawk/MainForm.Events.cs, src/BizHawk.Client.EmuHawk/MainForm.cs
- Ensure that the top left corner of the window remains on screen if the entire window cannot fit at 1x scale
- Fix title bar/menu moving off-screen with unusually large framebuffer sizes
- The bottom/right edge may move off-screen instead, but that seems like the lesser evil
- When `MainWindow.FrameBufferResized` is called while the window is minimized or maximized, defer the resize until the window is restored to normal again
- Fix window being disproportioned or moving erratically because the resize logic was working off of the minimized/maximized window sizes
- Remember window maximized state after restart
- This was intended to be part of #4011, but it depends on the previous fix to work properly
Resolves #2850
=> Main window auto-size fixes

src/BizHawk.Client.Common/tools/Cheat.cs, src/BizHawk.Client.Common/tools/CheatList.cs, src/BizHawk.Client.EmuHawk/MainForm.cs, src/BizHawk.Client.EmuHawk/tools/HexEditor/HexEditor.cs, src/BizHawk.Client.EmuHawk/tools/ToolManager.cs, src/BizHawk.Client.EmuHawk/tools/Watch/RamSearch.cs, src/BizHawk.Client.EmuHawk/tools/Watch/RamWatch.cs
Some fixes to how the cheat list is saved/loaded during rom load/close
- Fix cheat file for different game being deleted when switching roms while the Cheat window is open (resolve #3085)
- Ensure that cheats referencing disposed memory domains are either cleared or updated
- Fix access violation when closing rom while the Cheat window is open
- Fix access violation when loading rom while the Cheat window is open and `Config.Cheats.LoadFileByGame` is disabled
=> Cheat load/save fixes

src/BizHawk.Client.Common/RomLoader.cs, src/BizHawk.Client.EmuHawk/RetroAchievements/RetroAchievements.GameVerification.cs, src/BizHawk.Emulation.DiscSystem/DiscHasher.cs
Fix `DiscHasher.OldHash()` method used to hash non-PSX discs
- Don't hash generated (empty) lead-in/lead-out tracks
- Limit to track length, not absolute LBA of next track
Previously, Saturn and Sega CD discs are all hashed to the same value `D41D8CD98F00B204E9800998ECF8427E` (empty sequence). This happens because the method is trying to hash the non-existent lead-in track and `track.NextTrack.LBA` is `0` (the LBA of the "real" first track).
Hashing PC Engine discs already mostly worked because the first track is usually an audio track and the lead-in track copies the mode of the first track and is skipped. A handful of discs where the first data track is <512 sectors may generate a different hash now, because the old implementation was reading past the end of the track. The only examples …
=> Fix Sega CD/Saturn disc hashing

src/BizHawk.Client.Common/Api/Classes/JoypadApi.cs, src/BizHawk.Client.Common/DisplayManager/OSDManager.cs, src/BizHawk.Client.Common/controllers/StickyControllers.cs, src/BizHawk.Client.Common/inputAdapters/BitwiseAdapters.cs, src/BizHawk.Client.Common/inputAdapters/InputManager.cs, src/BizHawk.Client.Common/movie/MovieSession.cs, src/BizHawk.Client.Common/movie/bk2/Bk2Controller.cs, src/BizHawk.Client.Common/movie/interfaces/IMovieController.cs, src/BizHawk.Client.Common/movie/interfaces/IMovieSession.cs, src/BizHawk.Client.Common/movie/tasproj/TasMovie.Editing.cs, src/BizHawk.Client.EmuHawk/MainForm.Events.cs, src/BizHawk.Client.EmuHawk/MainForm.cs, src/BizHawk.Client.EmuHawk/config/AutofireConfig.cs, src/BizHawk.Client.EmuHawk/tools/TAStudio/TAStudio.ListView.cs, src/BizHawk.Client.EmuHawk/tools/TAStudio/TAStudio.cs, src/BizHawk.Client.EmuHawk/tools/VirtualPads/VirtualPad.cs, src/BizHawk.Client.EmuHawk/tools/VirtualPads/controls/VirtualPadAnalogButton.cs, src/BizHawk.Client.EmuHawk/tools/VirtualPads/controls/VirtualPadAnalogStick.cs, src/BizHawk.Client.EmuHawk/tools/VirtualPads/controls/VirtualPadButton.cs, src/BizHawk.Client.EmuHawk/tools/VirtualPads/controls/VirtualPadDiscManager.cs, src/BizHawk.Client.EmuHawk/tools/VirtualPads/controls/VirtualPadTargetScreen.cs, src/BizHawk.Client.EmuHawk/tools/VirtualPads/controls/components/AnalogStickPanel.cs
I've refactored the entire sticky controller / adapter thing because it felt bad and inconsistent, and made it so sticky input is now set into a controller instead of being inherently overlayed on top of an existing `IController` source.
This has a couple of advantages, mainly TAStudio being able to use sticky input directly while ignoring user input. There's tons of bugs with autofire/autohold in TAStudio still, but this should be a step in the right direction.
Previous logic:
Userinput is fed into the StickyXorAdapter, where bool buttons are xor'd with the sticky value, and axis values are OR'd with the source, prioritising sticky axis value over user input axis value.
Then that output is fed into the AutofireStickyXorAdapter, where bool buttons are xor'd with the autofire value and …
=> Refactor sticky controller logic to separate it from user input

src/BizHawk.Client.Common/movie/tasproj/ZwinderStateManager.cs, src/BizHawk.Client.Common/rewind/ZeldaWinder.cs, src/BizHawk.Client.Common/rewind/Zwinder.cs, src/BizHawk.Client.Common/rewind/ZwinderBuffer.cs
Addresses the slowdown concerns mentioned in https://github.com/TASEmulators/BizHawk/issues/4058#issuecomment-2381383751.
This changeset increases my fps in recording mode from ~3700 fps to ~5500 fps.
PRing because this touches state invalidation logic and I'd like to get at least a second pair of eyes on this to make sure it's correct and doesn't change any logic.
=> Move ZwinderBuffer invalidation logic into the class

src/BizHawk.Client.EmuHawk/config/FirmwaresConfig.cs, src/BizHawk.Emulation.Common/Database/FirmwareDatabase.cs
there's some discrepancy between the 2 orders, because the GUI list relies on full names (of the groups) while in the code short names are used to add them to DB
=> order firmware groups in the dialog and in the code

src/BizHawk.Client.EmuHawk/RetroAchievements/RetroAchievements.GameVerification.cs
Minor fix for games like Chrono Cross where the SYSTEM.CNF file contains a slightly different BOOT line than expected:
"BOOT\t= cdrom:" vs
"BOOT = cdrom:"
Additional fix for games like Tekken 3 and Wild Arms where the PlayStation executable is in a subdirectory.  For example:
BOOT = cdrom:\TEKKEN3\SLUS_004.02;1 or
BOOT = cdrom:\EXE\SCUS_946.08;1
In these cases, the application would get stuck in an infinite loop while looking for the executable filename in the same disc sector.  I believe this is related to a previously closed issue (#3863).
=> Fixes for PlayStation RetroAchievements hashing

src/BizHawk.Client.Common/lua/ILuaLibraries.cs, src/BizHawk.Client.EmuHawk/tools/Lua/LuaConsole.cs, src/BizHawk.Client.EmuHawk/tools/Lua/LuaLibraries.cs
Rework the way the Lua console REPL executes commands
The old way first tries to execute `$"console.log({rawCommand})"`, which prints out the values of an entered expression, but results in a syntax error if the command is a statement such as `foo = 1`. If the first attempt errors, it executes the raw command without the log call, so the command still works, but it's printing out confusing syntax error messages anyway. If the expression itself causes an error like `"a" + 1` or `string.format("%error")`, it tries to run it twice and prints out two different errors.
The PR changes it so `LuaLibraries.ExecuteString` attempts to first parse the modified command without running it, and then only executes either the modified command or the raw command. This avoids unnecessary error messages, …
=> Improve Lua REPL handling of statements

src/BizHawk.Emulation.Cores/Computers/Commodore64/FFT.cs, src/BizHawk.Emulation.Cores/Computers/Commodore64/MOS/Sid.cs
This change fixes the following issue:
https://github.com/TASEmulators/BizHawk/issues/4153
It also changes the FFT code path to reuse the FFT instance.
=> [C64] Fix filter stage passing sound when no filters are enabled

src/BizHawk.Emulation.Cores/Computers/Commodore64/C64.IMemoryDomains.cs, src/BizHawk.Emulation.Cores/Computers/Commodore64/C64.cs, src/BizHawk.Emulation.Cores/Computers/Commodore64/Cartridge/Am29F040B.cs, src/BizHawk.Emulation.Cores/Computers/Commodore64/Cartridge/CartridgeChip.cs, src/BizHawk.Emulation.Cores/Computers/Commodore64/Cartridge/CartridgeDevice.cs, src/BizHawk.Emulation.Cores/Computers/Commodore64/Cartridge/CartridgePort.cs, src/BizHawk.Emulation.Cores/Computers/Commodore64/Cartridge/Mapper0020.cs
- Implement the AM29F040B flash device as its own component
- Fix save data for games that use the standard EasyAPI driver
- Fix "Briley Witch Chronicles 2": the flash driver checks AutoSelect register 02 to see if the cartridge is write-protected
- Rom is stored as bytes instead of ints, saves a lot of memory
- EasyFlash now has proper hard reset and clock operations
- SaveRam deltas fixed
- Flash …
=> [C64] EasyFlash overhaul

src/BizHawk.Emulation.Cores/Computers/Commodore64/Cartridge/CartridgeChip.cs, src/BizHawk.Emulation.Cores/Computers/Commodore64/Cartridge/CartridgeDevice.cs, src/BizHawk.Emulation.Cores/Computers/Commodore64/Cartridge/Mapper0013.cs
- Make it possible to load Domark/HES/MagicDesk cartridge images that don't have a power-of-two bank count
- Add a memory domain for the ROM image
- Increase the maximum bank count from 16 to 128; this should account for literally any dump using this mapper
[//]: # "Apart from the mandatory license signature, these tasks are optional, but doing them could save reviewers some time and get the PR merged …
=> [C64] Fix Domark/HES/MagicDesk cartridge mapper bank loading

src/BizHawk.Emulation.Cores/Computers/Commodore64/Media/Disk.cs, src/BizHawk.Emulation.Cores/Computers/Commodore64/Media/DiskTrack.cs, src/BizHawk.Emulation.Cores/Computers/Commodore64/Serial/Drive1541.FluxTransitions.cs, src/BizHawk.Emulation.Cores/Computers/Commodore64/Serial/Drive1541.SaveRam.cs, src/BizHawk.Emulation.Cores/Computers/Commodore64/Serial/Drive1541.cs
Addresses https://github.com/TASEmulators/BizHawk/issues/4151
Causes:
- "Save RAM modified" flag is always True
- Deltas are calculated each frame due to the aforementioned flag
- Excess array allocations in the C64 core during delta calculation
Solutions:
- Fewer runtime array allocations (re-use buffers)
- Proper implementation of "save RAM modified" flag (only set when the disk data has changed since the last save)
- Instead of tracking which disk tracks are used at all, track which disk tracks are modified
- Store deltas only for tracks that have been modified
Practical tests run:
- Performance monitoring
- Load and save state using C64 disk media (D64, PRG)
- Load and save state on some other cores
Before changes, using Remember's release of "Uridium":
After changes, using the same …
=> [C64] Fix memory performance issues

README.md
[rendered](https://github.com/TASEmulators/BizHawk/blob/readme-updates/README.md)
=> Post-2.10 readme updates

src/BizHawk.Client.Common/Api/HttpCommunication.cs, src/BizHawk.Client.Common/lua/CommonLibs/CommLuaLibrary.cs
Fixes #4187 
Add a method to allow setting the ExpectContinue functionality in the C#.NET to off or on explicitly, allowing compatibility with servers that don't support the default "Expect: 100-Continue" header that C#.NET defaults to sending for POST requests.
I have done a test build but not directly tested the functionality as of yet.
[//]: # "Apart from the mandatory license signature, these tasks …
=> Add a method to the `comm` Lua library to allow setting `ExpectContinue`

src/BizHawk.Emulation.Cores/CPUs/MOS 6502X/Execute.cs, src/BizHawk.Emulation.Cores/CPUs/MOS 6502X/MOS6502X.cs, src/BizHawk.Emulation.Cores/Computers/Commodore64/MOS/Chip6510.cs, src/BizHawk.Emulation.Cores/Computers/Commodore64/Serial/Drive1541.cs
This change makes the 6502 opcode tests (not specific to 6510 I/O behavior) pass on the M6502X CPU core:
- Fix decimal mode SBC implementation (flags improperly set)
- Add ANE implementation
- Implement SHA/SHX/SHY page correction behavior and RDY pin interaction
- Allow system cores to configure the "constant" values for ANE and LXA, this is implemented like a register that can be "read". Not all manufactured 6502 derivatives will have identical values, but should mostly be consistent among the same make and model of CPU
See more in this issue: https://github.com/TASEmulators/BizHawk/issues/4176
This is a draft because we will want input from other system core developers who maintain cores that use the M6502X CPU core.
=> [6502] Pass Lorenz C64 tests

src/BizHawk.Emulation.Cores/Computers/Commodore64/MOS/Cia.Registers.cs, src/BizHawk.Emulation.Cores/Computers/Commodore64/MOS/Cia.cs, src/BizHawk.Emulation.Cores/Computers/Commodore64/MOS/Via.Registers.cs, src/BizHawk.Emulation.Cores/Computers/Commodore64/MOS/Via.cs, src/BizHawk.Emulation.Cores/Computers/Commodore64/Media/DiskTrack.cs, src/BizHawk.Emulation.Cores/Computers/Commodore64/Serial/Drive1541.FluxTransitions.cs, src/BizHawk.Emulation.Cores/Computers/Commodore64/Serial/Drive1541.Motor.cs, src/BizHawk.Emulation.Cores/Computers/Commodore64/Serial/Drive1541.Registers.cs, src/BizHawk.Emulation.Cores/Computers/Commodore64/Serial/Drive1541.SaveRam.cs, src/BizHawk.Emulation.Cores/Computers/Commodore64/Serial/Drive1541.cs
Alright friends, this one's been on my to-do list for a long time and I've made a push to fix some of the more notoriously picky disk loaders. The disk changes from here on out will likely be far less substantial (though there will be a few odd cases yet to fix- those will get their own work later.)
Disk checking utilities will now work and you can also run format commands without it erroring out now. This came down to how sparse we were putting the bits on the magnetic media. There's a neat little "feature" of the drive hardware where if you space your bits too far apart, you can get ghost bits clocked into the shift register. It's a bug that has been emulated, but it was being triggered on media that was properly formatted in the first place.
The quick and dirty changelog:
[C64] Disk: …
=> [C64] 1541 disk drive emulation facelift

src/BizHawk.Client.Common/Api/Classes/EmulationApi.cs
Implement emu.setrenderplanes for snes9x
=> implement emu.setrenderplanes in EmulationApi for snes9x

src/BizHawk.Client.EmuHawk/tools/Lua/Libraries/TAStudioLuaLibrary.cs
Implements four new lua functions:
- tastudio.getmarkerabove(frame)
returns a table with fields Frame and Text for the marker that is at or above the given frame, where the field Frame is the actual frame where the marker is located
- tastudio.getmarkers()
returns a list with all markers for the loaded movie, for which each entry has a table with fields Frame and Text
- tastudio.getbranchmarkerabove(branchId, frame)
returns a table with fields Frame and Text for the marker that is at or above the given frame for the given branchId
- tastudio.getbranchmarkers(branchId)
returns a list with all markers for the loaded movies for the given branchId
Those functions returned the tables in with no time drawbacks in constant time.
With those function it's possible to do what's possible in FCEUX …
=> TAStudio marker lua 

README.md
Since the `bizhawk-monort` AUR package got merged with the [`bizhawk-bin`](https://aur.archlinux.org/packages/bizhawk-bin) one two days ago, here's a PR fixing the link in the README, as well as changing the badge to Arch Linux instead, since Manjaro is based on Arch Linux and any distro based on it can use the AUR.
Also changed the text in the "Misc. Linux" badge to "binaries" to match with Windows' badge.
=> Update AUR package link in the README

src/BizHawk.Emulation.Cores/Computers/MSX/MSX.cs, src/BizHawk.Emulation.Cores/Consoles/Atari/A7800Hawk/A7800Hawk.cs, src/BizHawk.Emulation.Cores/Consoles/GCE/Vectrex/VectrexHawk.cs, src/BizHawk.Emulation.Cores/Consoles/Magnavox/Odyssey2/O2Hawk.cs, src/BizHawk.Emulation.Cores/Consoles/Nintendo/3DS/Encore.cs, src/BizHawk.Emulation.Cores/Consoles/Nintendo/BSNES/SubBsnesCore.cs, src/BizHawk.Emulation.Cores/Consoles/Nintendo/GBHawk/GBHawk.cs, src/BizHawk.Emulation.Cores/Consoles/Nintendo/GBHawkLink/GBHawkLink.cs, src/BizHawk.Emulation.Cores/Consoles/Nintendo/GBHawkLink3x/GBHawkLink3x.cs, src/BizHawk.Emulation.Cores/Consoles/Nintendo/GBHawkLink4x/GBHawkLink4x.cs, src/BizHawk.Emulation.Cores/Consoles/Nintendo/N64/N64.cs, src/BizHawk.Emulation.Cores/Consoles/Nintendo/SNES9X/Snes9x.cs, src/BizHawk.Emulation.Cores/Consoles/Nintendo/SubGBHawk/SubGBHawk.cs, src/BizHawk.Emulation.Cores/Consoles/Nintendo/SubNESHawk/SubNESHawk.cs, src/BizHawk.Emulation.Cores/Consoles/Sega/GGHawkLink/GGHawkLink.cs
Please double-check I have all this correct.
CC @alyosha-tas since half of these are yours.
This is a step towards [respecting all intellectual property](https://gitlab.com/YoshiRulz/yoshis-hawk-thoughts/-/issues/61) of our subprojects and dependencies.
=> Update author/source metadata for several cores where it's missing

src/BizHawk.Emulation.Cores/Consoles/Nintendo/NES/NES.Core.cs
Reading from $4015 no longer updates the data bus.
Per the [NesDev Wiki](https://www.nesdev.org/wiki/APU#Status_($4015)):
> This register is internal to the CPU and so the external CPU data bus is disconnected when reading it. Therefore the returned value cannot be seen by external devices and the value does not affect [open bus](https://www.nesdev.org/wiki/Open_bus_behavior).
This can very easily be tested by running
LDX #$16
LDA $40FF, X
The dummy read cycle will read from $4015 before the CPU will read from $4115, returning open bus. If the dummy read of $4015 incorrectly updates the data bus, then the result would be zero:
But by correcting this behavior, the value of $40 (from reading the second operand) remains on the data bus even after the dummy read cycle.
=> Fix NesHawk APU Status open bus behavior

src/BizHawk.Client.Common/movie/MovieSession.cs, src/BizHawk.Client.Common/movie/bk2/Bk2Movie.ModeApi.cs, src/BizHawk.Client.Common/movie/interfaces/IMovie.cs
If the user closed a movie in TAStudio while in recording mode and clicked "no" when asked if they want to save, the movie would get saved anyway. The recording mode check doesn't seem to do any good; if the user has recorded anything (or truncated the movie by loading a savestate to enter recording mode) then `Changes` will be set. From looking at the commit history, the check for recording mode was implemented before recording itself was implemented. So it probably should never have been there to begin with.
Edit: To clarify, this bug only actually happens if you open a (new or existing) movie while in recording mode, and not if you close TAStudio.
It's unclear why there is also a check for `IsActive`. It probably isn't doing any harm, but it is confusing. Commit …
=> Don't save when the user says no.

src/BizHawk.Client.EmuHawk/IMainFormForTools.cs, src/BizHawk.Client.EmuHawk/MainForm.cs, src/BizHawk.Client.EmuHawk/tools/TAStudio/TAStudio.Designer.cs, src/BizHawk.Client.EmuHawk/tools/TAStudio/TAStudio.IControlMainForm.cs, src/BizHawk.Client.EmuHawk/tools/TAStudio/TAStudio.MenuItems.cs, src/BizHawk.Client.EmuHawk/tools/TAStudio/TAStudio.cs
Currently, rewinds in TAStudio always go back exactly 1 frame.
This patch adds the following features to TAStudio:
- Rewinds now go back a X frames.
- While fast-forwarding, rewinds instead go back Y frames.
- X and Y are configurable. The default values are X=1 and Y=4.
Broadly speaking, there are 3 ways of tasing in Bizhawk. This patch only affects (2).
1) use saves states and rewinds, but not TAStudio (aka the piano roll).
2) use TAStudio keyboard only and navigate with the frame advance and rewind keys.
3) use TAStudio with a mouse and paint inputs on the piano roll.
Each of these has advantages and disadvantages. From my experience: (2) is more versatile than (1), since you can go back and edit inputs; and (2) is faster than (3) when playing a section for the first time, since you …
=> Make the number of frames per TAStudio rewind configurable.

src/BizHawk.Emulation.Cores/CPUs/MOS 6502X/Execute.cs, src/BizHawk.Emulation.Cores/CPUs/MOS 6502X/MOS6502X.cs, src/BizHawk.Emulation.Cores/Computers/Commodore64/MOS/Chip6510.cs, src/BizHawk.Emulation.Cores/Consoles/Nintendo/NES/APU.cs, src/BizHawk.Emulation.Cores/Consoles/Nintendo/NES/NES.Core.cs, src/BizHawk.Emulation.Cores/Consoles/Nintendo/NES/NES.IStatable.cs, src/BizHawk.Emulation.Cores/Consoles/Nintendo/NES/PPU.cs, src/BizHawk.Emulation.Cores/Consoles/Nintendo/NES/PPU.regs.cs, src/BizHawk.Emulation.Cores/Consoles/Nintendo/NES/PPU.run.cs, src/BizHawk.Emulation.Cores/Consoles/Nintendo/SubNESHawk/SubNESHawk.IEmulator.cs
Opcodes $93, $9B, $9C, $9E, and $9F, also referred to as the "Unstable High Byte Group", all rely on the High Byte of the target address being incremented internally when the processor adds the X or Y register as an offset, and this new value of the high byte is ANDed with the value being stored.
In addition to adding the byte H, which is currently only updated in the relevant cycles for the Unstable High Byte Group instructions, I also added the private void AbsIdx_Stage4_SHS(), which is pretty much the same as AbsIdx_Stage4() but it updates H. I've removed some lines from the various AbsIdx_WRITE_Stage5 functions which were incorrectly modifying the target address "ea".
I also renamed AbsIdx_WRITE_Stage5_ERROR to AbsIdx_WRITE_Stage5_SHS
This should now match the behavior documented in …
=> Fixed incorrect behavior of SHA, SHX, SHY, and SHS in NesHawk

src/BizHawk.Client.Common/config/Binding.cs, src/BizHawk.Client.EmuHawk/MainForm.Events.cs, src/BizHawk.Client.EmuHawk/MainForm.Hotkey.cs, src/BizHawk.Client.EmuHawk/tools/TAStudio/MarkerControl.cs, src/BizHawk.Client.EmuHawk/tools/TAStudio/PlaybackBox.cs, src/BizHawk.Client.EmuHawk/tools/TAStudio/TAStudio.ListView.cs, src/BizHawk.Client.EmuHawk/tools/TAStudio/TAStudio.MenuItems.cs, src/BizHawk.Client.EmuHawk/tools/TAStudio/TAStudio.cs, src/BizHawk.Client.EmuHawk/tools/ToolFormBase.cs, src/BizHawk.Client.EmuHawk/tools/ToolManager.cs
Hotkeys:
Add marker (default M): Adds a marker to the emulated frame, same as the add marker button under the markers list.
Delete marker (default Ctrl+M): Deletes a marker on the emulated frame
Seek to prev/next marker (default Shift+PageUp/Down): Already existed, they are just now configurable.
=> Add some hotkeys for markers, and display them in tool tips.

src/BizHawk.Client.Common/Controller.cs, src/BizHawk.Client.Common/config/Config.cs, src/BizHawk.Client.Common/controllers/StickyControllers.cs, src/BizHawk.Client.Common/input/IPhysicalInputSource.cs, src/BizHawk.Client.Common/input/InputCoalescerControllers.cs, src/BizHawk.Client.Common/inputAdapters/InputManager.cs, src/BizHawk.Client.EmuHawk/Input/Input.cs, src/BizHawk.Client.EmuHawk/MainForm.Events.cs, src/BizHawk.Client.EmuHawk/MainForm.Hotkey.cs, src/BizHawk.Client.EmuHawk/MainForm.cs, src/BizHawk.Tests.Client.Common/InputManagerTests.cs, src/BizHawk.Tests.Client.Common/Movie/FakeMovieSession.cs, src/BizHawk.Tests.Client.Common/Movie/TasMovieTests.cs, src/BizHawk.Tests.Client.Common/input/FakeInputSource.cs
Fix: Hotkey overrides input would cause an input to continue after a button was released if the input is bound to a combination such as Shift+A and an "internal hotkey" is bound to a single button (such as A). Also input bound to Alt would not have the alt ignored by menus.
Fix: Input overrides hotkeys did not work if both input and hotkey were bound to a combination such as Shift+A.
Fix: Controller inputs bound to a modifier key combination would not be triggered if additional modifier keys were also pressed.
Fix: autofire/autohold hotkeys would sometimes activate buttons that were already being held when the hotkey was pressed.
Check …
=> Fix input/hotkey bugs

src/BizHawk.Client.EmuHawk/tools/TAStudio/TAStudio.MenuItems.cs
I sometimes find that I am unable to copy/paste inputs in TAStudio. Maybe this fixes it. It does fix this particular situation:
1) Click the marker list or another control to ensure it has focus
2) Do not move the mouse over the input list
3) Alt+tab to another window
4) Alt+tab back
5) Try to copy with Ctrl+C.
~~This might not fix it in every case. There have been several times when I am unable to copy/paste with the keyboard even after clicking the input list, moving the mouse around, clicking another window then going back to TAStudio... nothing seems to work. I have no idea how to reproduce that, but I do know by using the debugger that when it happens pressing Ctrl+C does not enter `CopyMenuItem_Click`.~~ That issue has been fixed.
=> Fix a situation where copy/paste hotkeys don't work.

src/BizHawk.Client.EmuHawk/tools/Lua/LuaDropDown.cs
Check if list of items is empty before setting `SelectedIndex`, to avoid an `ArgumentOutOfRangeException`.
=> Fix error when creating empty Lua form dropdowns

src/BizHawk.Client.EmuHawk/IControlMainform.cs, src/BizHawk.Client.EmuHawk/MainForm.cs, src/BizHawk.Client.EmuHawk/tools/TAStudio/TAStudio.IControlMainForm.cs, src/BizHawk.Client.EmuHawk/tools/TAStudio/TAStudio.IToolForm.cs, src/BizHawk.Client.EmuHawk/tools/TAStudio/TAStudio.ListView.cs, src/BizHawk.Client.EmuHawk/tools/TAStudio/TAStudio.MenuItems.cs, src/BizHawk.Client.EmuHawk/tools/TAStudio/TAStudio.Navigation.cs, src/BizHawk.Client.EmuHawk/tools/TAStudio/TAStudio.cs
Several fixes to seeking behavior.
This PR introduces a change to how a return value from the API is used: The value of `Rewind` is no longer ignored. What it signifies is also slightly different. It used to say "if the rewind occurred" but now "if a frame advance is required". (In TAStudio, these were usually the same thing.) The ApiHawk [changelog](https://github.com/TASEmulators/BizHawk-ExternalTools/wiki/Partial-changelog-for-ApiHawk) should be updated.
Bugs that affect 2.10:
1. Wheel scroll up behavior was inconsistent, depending on if one or two events are raised for a two-notch scroll.
2. Green arrow was not reset when loading a new movie.
3. Seek would be canceled if user triggers a TAStudio close but cancels when asked if they want to save.
4. Starting a new movie then unpausing …
=> Seek fixes

src/BizHawk.Client.Common/lua/NLuaTableHelper.cs, src/BizHawk.Client.EmuHawk/tools/Lua/Libraries/FormsLuaLibrary.cs
- Add `NLuaTableHelper.EnumerateAllValues` which works like the old `EnumerateValues` implementation before 7bd9e218
- Add doc comments to both methods to clarify the difference
- Use this new (old) method in `FormsLuaLibrary.Dropdown` and `SetDropdownItems` to restore old behavior
7bd9e218 changed the behavior of `NLuaTableHelper.EnumerateValues` to enumerate keys sequentially and ignore non-sequential/non-numeric keys, the way Lua's `ipairs` does it. This makes sense for most uses of `EnumerateValues`, but `forms.dropdown` is explicitly documented as not requiring numeric/sequential keys, and some scripts* rely on this behavior. `forms.setdropdownitems` doesn't document what the table should look like, but can be assumed to work the same.
\* I ran into this issue while testing the …
=> Fix some items not appearing in Lua form dropdowns

src/BizHawk.Client.EmuHawk/tools/Lua/Libraries/TAStudioLuaLibrary.cs
Based on #4272 by @c7fab (thank you, and please let us know if this is insufficient for your use case).
=> Add more Lua functions for TAStudio markers

src/BizHawk.Client.Common/RomLoader.cs
Fix "The file needs to exist, yo." exception when loading a libretro core with the "no game" option after 0681dd2590ffe8e68e3383d273566118e557c6bb.
=> Fix libretro "no game" loading

src/BizHawk.Client.Common/Api/Classes/InputApi.cs, src/BizHawk.Client.Common/Api/Interfaces/IInputApi.cs, src/BizHawk.Client.Common/input/InputCoalescerControllers.cs, src/BizHawk.Client.Common/inputAdapters/InputManager.cs, src/BizHawk.Tests.Client.Common/Api/InputApiTests.cs, src/BizHawk.Tests.Client.Common/InputManagerTests.cs, src/BizHawk.Tests.Client.Common/input/FakeInputSource.cs
See issue #4449 
It is questionable if the accidental change to the API behavior is good. This PR restores the old behavior and updates the API documentation to clarify behavior. (with the caveat that hotkey priority can no longer hide inputs from the API)
Note that the new `ApiInputCoalescer` class would not be necessary if we do not want controllers to see holding A and pressing Shift as Shift+A.
If there is consensus that we want to do this, I will update the comments in the test code and merge.
=> Fix InputApi

src/BizHawk.Client.Common/config/MovieConfig.cs, src/BizHawk.Client.Common/movie/interfaces/ITasMovie.cs, src/BizHawk.Client.Common/movie/tasproj/IStateManager.cs, src/BizHawk.Client.Common/movie/tasproj/IStateManagerSettings.cs, src/BizHawk.Client.Common/movie/tasproj/StatableStream.cs, src/BizHawk.Client.Common/movie/tasproj/TasMovie.IO.cs, src/BizHawk.Client.Common/movie/tasproj/TasMovie.cs, src/BizHawk.Client.Common/movie/tasproj/ZwinderStateManager.cs, src/BizHawk.Client.Common/movie/tasproj/ZwinderStateManagerSettings.cs, src/BizHawk.Client.Common/rewind/ZwinderBuffer.cs, src/BizHawk.Client.Common/tools/TAStudio/PagedStateManager.cs, src/BizHawk.Client.EmuHawk/tools/TAStudio/GreenzoneSettings.cs, src/BizHawk.Client.EmuHawk/tools/TAStudio/TAStudio.Designer.cs, src/BizHawk.Client.EmuHawk/tools/TAStudio/TAStudio.MenuItems.cs, src/BizHawk.Tests.Client.Common/Movie/FakeMovieSession.cs, src/BizHawk.Tests.Client.Common/Movie/FakeStateManager.cs, src/BizHawk.Tests.Client.Common/Movie/PagedStateManagerTests.cs, src/BizHawk.Tests.Client.Common/Movie/ZwinderStateManagerTests.cs, src/BizHawk.Tests.Client.Common/config/SerializationStabilityTests.cs
This PR writes a new state manager. It takes some inspiration from the current Zwinder manager, but has a few differences. The primary goal of this state manager was to enable capturing states out of order. This provides two primary benefits:
1) Users who load a branch, emulate forward a little, then rewind can still use the full buffer space.
2) It becomes much easier to "thin out" states (keeping only a subset of them) for saving and to then use them again on load. With the default settings, auto-save is now much less annoying.
In my very limited testing, performance seems virtually identical, except when re-playing an old part of a movie where it will be capturing states (what Zwinder calls "gap states"), for movies with a large number of states. That's slower due to a stupid of .NET's …
=> Implement a new TAS state manager
