TASEmulators/BizHawk

BizHawk.Client.Common/BizHawk.Client.Common.csproj
BizHawk.Client.Common/movie/import/MovieImport.cs
BizHawk.Client.Common/movie/import/PJMImport.cs
BizHawk.Client.Common/movie/import/PXMImport.cs
BizHawk.Client.EmuHawk/MainForm.Events.cs
BizHawk.Emulation.Cores/Consoles/Sony/PSX/Octoshock.cs

Implemented reflection-based dispatching (mentioned in adelikat's TODO) 
Implemented PJM and PXM imports using the above mechanism 
One main thing I'm not sure about in my implementation is that I exposed 
the controller definition from Octoshock publicly as a static method to 
create the controller for input data. Was there another way I should 
have done that? Would SimpleController have been enough?

Movies: Reflection-based dispatching; PJM/PXM imports

---

BizHawk.Client.EmuHawk/tools/BasicBot/BasicBot.Designer.cs

Aligns input frame readout by using a monospaced font for the display

Monospaced font for BasicBot input display

---

BizHawk.Client.EmuHawk/tools/Lua/Libraries/EmuLuaLibrary.Forms.cs
BizHawk.Client.EmuHawk/tools/Lua/Libraries/EmuLuaLibrary.cs

Fix forms.destroyall() and call it when lua console closes

---

BizHawk.Client.EmuHawk/tools/BasicBot/BasicBot.Designer.cs
BizHawk.Client.EmuHawk/tools/BasicBot/BasicBot.cs
BizHawk.Client.EmuHawk/tools/BasicBot/BotControlsRow.Designer.cs

Used visual studio windows forms editor to reduce window size of basic bot. 
Please check this out and see if the window size is appropriate. I tried to mimic the Dec 2015 release as much as possible given the addition of the new UI elements

reduced basic bot window size

---

BizHawk.Emulation.Cores/Consoles/Atari/2600/Tia/TIA.cs
BizHawk.Emulation.Cores/Consoles/Atari/2600/Tia/Tia.MissleData.cs
TIA.cs

Following bug fixes:
Latch delays for various instructions including enables, graphics, and reset
Fixes screen color during HMove
Fixes resp/HMove interation
Fixes HMove counter

AtariHawk bug fixes pull request

---

BizHawk.Emulation.Cores/Consoles/Atari/2600/Atari2600.Core.cs
BizHawk.Emulation.Cores/Consoles/Atari/2600/M6532.cs
BizHawk.Emulation.Cores/Consoles/Atari/2600/Mappers/mCM.cs
BizHawk.Emulation.Cores/Consoles/Atari/2600/Tia/TIA.cs

Still a WIP
Fixes numerous bugs to get system running, but needs keyboard for further testing.

Initial PR for Compumate

---

BizHawk.Emulation.Cores/Consoles/Atari/2600/Tia/Tia.Audio.cs

This actually affected several other sound channels as well since the old code put the other poly counters into degenerate states at times

fixes poly9 sound

---

BizHawk.Emulation.Cores/Consoles/Nintendo/NES/PPU.regs.cs
BizHawk.Emulation.Cores/Consoles/Nintendo/NES/PPU.run.cs

Fix a bug in OAM regs

---

BizHawk.Emulation.Cores/CPUs/MOS 6502X/Execute.cs
Execute.cs

effects dummy reads (such as NOP)

Another read / RDY fix

---

BizHawk.Client.EmuHawk/tools/NES/NESPPU.Designer.cs
BizHawk.Emulation.Cores/Consoles/Nintendo/NES/NES.Core.cs

Changed the size of pallete and sprite boxes in PPU viewer to avoid out of bounds errors. 
(Let me know if I did something wrong there.)
pases:
cpu_exec_space/test_cpu_exec_space_apu

PPU viewer and APU open bus fixes

---

BizHawk.Emulation.Cores/Consoles/Nintendo/NES/APU.cs
BizHawk.Emulation.Cores/Consoles/Nintendo/NES/NES.Core.cs
BizHawk.Emulation.Cores/Consoles/Nintendo/NES/NES.IStatable.cs
BizHawk.Emulation.Cores/Consoles/Nintendo/NES/PPU.cs
BizHawk.Emulation.Cores/Consoles/Nintendo/NES/PPU.regs.cs

Pass a few more tests

---

APU.cs
BizHawk.Emulation.Cores/Consoles/Nintendo/NES/APU.cs
BizHawk.Emulation.Cores/Consoles/Nintendo/NES/PPU.regs.cs
PPU.regs.cs

Start clean up of APU as well.

Fix Saint Saiya

---

BizHawk.Client.EmuHawk/MainForm.Designer.cs
BizHawk.Client.EmuHawk/MainForm.Events.cs
BizHawk.Emulation.Cores/Consoles/Sega/SMS/SMS.ISettable.cs
BizHawk.Emulation.Cores/Consoles/Sega/SMS/SMS.cs
BizHawk.Emulation.Cores/Consoles/Sega/SMS/VDP.Mode4.cs
BizHawk.Emulation.Cores/Consoles/Sega/SMS/VDP.cs

Cherry-picked vecna's fork's commit. SMS overscan allows for proper encoding and fixes #642.

SMS overscan display

---

BizHawk.Emulation.Cores/Consoles/Nintendo/NES/Boards/MMC3_family/MMC3.cs
BizHawk.Emulation.Cores/Consoles/Nintendo/NES/PPU.cs
BizHawk.Emulation.Cores/Consoles/Nintendo/NES/PPU.regs.cs
BizHawk.Emulation.Cores/Consoles/Nintendo/NES/PPU.run.cs

Fixes Burai Fighter
Fixes Recca
Fixes Mickey Safari in Letter Land

Update MMC3 A-12 Clocking

---

BizHawk.Client.Common/config/Binding.cs
BizHawk.Client.EmuHawk/MainForm.Designer.cs
BizHawk.Client.EmuHawk/MainForm.Events.cs
BizHawk.Client.EmuHawk/MainForm.Hotkey.cs
BizHawk.Client.EmuHawk/MainForm.cs
BizHawk.Client.EmuHawk/tools/Lua/Libraries/EmuLuaLibrary.Client.cs

I added a hotkey to flush saveram, and exposed that function to lua.  Both call the standard SaveRam() method called by the Save RAM -> Flush Save Ram menu item.

flush Saveram via hotkey or lua

---

BizHawk.Client.EmuHawk/ArgParser.cs
BizHawk.Client.EmuHawk/BizHawk.Client.EmuHawk.csproj
BizHawk.Client.EmuHawk/MainForm.cs

tested the following arguments
--luaconsole
--lua=
--movie
load a ROM
doesn't seem to break anything.

added command line arguments parser

---

BizHawk.Client.EmuHawk/ArgParser.cs
BizHawk.Client.EmuHawk/MainForm.Events.cs
BizHawk.Client.EmuHawk/MainForm.cs

In #918 I forgot to include command line arguments where the variables start with `_`.
All command line arguments were tested and found to be working.

Added missing commandline arguments

---

BizHawk.Client.Common/lua/EmuLuaLibrary.Memory.cs

Resolves #730 
Call via `memory.hash_region(starting address, number of bytes to hash, [optional domain name])`
```lua
local hash = ""
local changes = 0
memory.usememorydomain("OAM")
while true do
local newHash = memory.hash_region(0x00, 0x100)
if newHash ~= hash then
changes = changes + 1
hash = newHash
console.log(changes..": "..hash)
end
gui.text(5, 5, 'Frames with OAM Changes: '..changes)
emu.frameadvance()
end
```

Adds Lua memory.hash_region() to aid in detecting RAM changes

---

BizHawk.Client.EmuHawk/MainForm.cs

Make Reboot Core not crash after Close ROM

---

BizHawk.Client.Common/movie/tasproj/TasStateManager.cs
BizHawk.Client.EmuHawk/tools/Lua/Libraries/EmuLuaLibrary.Tastudio.cs
BizHawk.Client.EmuHawk/tools/TAStudio/BookmarksBranchesBox.cs
BizHawk.Client.EmuHawk/tools/TAStudio/TAStudio.Callbacks.cs
BizHawk.Client.EmuHawk/tools/TAStudio/TAStudio.ListView.cs
BizHawk.Client.EmuHawk/tools/TAStudio/TAStudio.cs

lua functions for setting bool and float states in tastudio.
I'm not sure if it wouldn't be better to use the logic TAS Editor uses.

tastudio lua: setinput functions, onbranch callbacks

---

BizHawk.Client.EmuHawk/tools/Lua/LuaFunctionsForm.Designer.cs
BizHawk.Client.EmuHawk/tools/Lua/LuaFunctionsForm.cs
BizHawk.Common/Util.cs

All required contents for: https://github.com/TASVideos/BizHawk/issues/1122.

Context menu in Lua Functions window #1122

---

BizHawk.Client.EmuHawk/MainForm.cs

See ticket #1241 
This PR:
* Pushes a client OSD message to the screen when flushing saveRAM fails (also introduces a try/catch here in FlushSaveRAM() to avoid the reported exception loop)
* It also modifies the FlushSaveRAM() method to return a bool. This way CloseGame() is modified so that if FlushSaveRAM() return false, a MessageBox is shown to the user making them aware of the situation, and whether they really want to close.

EmuHawk: Handle SaveRAM IO errors - #1241

---

BizHawk.Emulation.Common/Database/FirmwareDatabase.cs
BizHawk.Emulation.Cores/BizHawk.Emulation.Cores.csproj
BizHawk.Emulation.Cores/Computers/SinclairSpectrum/Machine/MachineType.cs
BizHawk.Emulation.Cores/Computers/SinclairSpectrum/Machine/Pentagon128K/Pentagon128.Memory.cs
BizHawk.Emulation.Cores/Computers/SinclairSpectrum/Machine/Pentagon128K/Pentagon128.Port.cs
BizHawk.Emulation.Cores/Computers/SinclairSpectrum/Machine/Pentagon128K/Pentagon128.Screen.cs
BizHawk.Emulation.Cores/Computers/SinclairSpectrum/Machine/Pentagon128K/Pentagon128.cs
BizHawk.Emulation.Cores/Computers/SinclairSpectrum/ZXSpectrum.ISettable.cs
BizHawk.Emulation.Cores/Computers/SinclairSpectrum/ZXSpectrum.cs

Initial setup for pentagon emulation.

ZXHawk: pentagon initialisation

---

BizHawk.Emulation.Cores/CPUs/Z80A/Execute.cs
BizHawk.Emulation.Cores/CPUs/Z80A/Interrupts.cs
BizHawk.Emulation.Cores/CPUs/Z80A/Tables_Direct.cs
BizHawk.Emulation.Cores/CPUs/Z80A/Tables_Indirect.cs
BizHawk.Emulation.Cores/CPUs/Z80A/Z80A.cs

Z80A Optimizations

---

BizHawk.Client.EmuHawk/Throttle.cs

I've only found the one so far, so going to merge (and address anything else later).

Remove wine dependencies for linux

---

BizHawk.Client.DiscoHawk/About.cs
BizHawk.Client.DiscoHawk/AudioExtractor.cs
BizHawk.Client.DiscoHawk/DiscoHawk.cs
BizHawk.Client.DiscoHawk/MainDiscoForm.cs

Use string interpolation in BizHawk.Client.DiscoHawk

---

BizHawk.Client.ApiHawk/Classes/Api/JoypadApi.cs
BizHawk.Client.ApiHawk/Classes/Api/MemApiBase.cs
BizHawk.Client.ApiHawk/Classes/Api/MovieApi.cs
BizHawk.Client.ApiHawk/Classes/Api/SqlApi.cs
BizHawk.Client.ApiHawk/Classes/BizHawkSystemIdToCoreSystemEnumConverter.cs
BizHawk.Client.ApiHawk/Classes/ClientApi.cs
BizHawk.Client.ApiHawk/Classes/ExternalToolManager.cs
BizHawk.Client.ApiHawk/Classes/Joypad.cs
BizHawk.Client.ApiHawk/Classes/JoypadStringToEnumConverter.cs

Use string interpolation in BizHawk.Client.ApiHawk

---

BizHawk.Emulation.Common/Database/Database.cs
BizHawk.Emulation.Common/EmulationExceptions.cs
BizHawk.Emulation.DiscSystem/API_MednaDisc.cs
BizHawk.Emulation.DiscSystem/CDFS/ISOVolumeDescriptor.cs
BizHawk.Emulation.DiscSystem/DiscDecoding.cs
BizHawk.Emulation.DiscSystem/DiscExceptions.cs
BizHawk.Emulation.DiscSystem/DiscFormats/Blobs/RiffMaster.cs
BizHawk.Emulation.DiscSystem/DiscFormats/CCD_format.cs
BizHawk.Emulation.DiscSystem/DiscFormats/CUE/CUE_Compile.cs
BizHawk.Emulation.DiscSystem/DiscFormats/CUE/CUE_File.cs
BizHawk.Emulation.DiscSystem/DiscFormats/CUE/CUE_Load.cs
BizHawk.Emulation.DiscSystem/DiscFormats/CUE/CUE_Parse.cs
BizHawk.Emulation.DiscSystem/DiscFormats/CUE/CUE_Synths.cs
BizHawk.Emulation.DiscSystem/DiscFormats/MDS_Format.cs
BizHawk.Emulation.DiscSystem/DiscMountJob.cs
BizHawk.Emulation.DiscSystem/DiscTypes.cs

Use string interpolation in BizHawk.Emulation.Common and BizHawk.Emulation.DiscSystem

---

BizHawk.Common/BinaryQuickSerializer.cs
BizHawk.Common/BizInvoke/BizExvoker.cs
BizHawk.Common/BizInvoke/BizInvokeUtilities.cs
BizHawk.Common/BizInvoke/BizInvoker.cs
BizHawk.Common/Extensions/BufferExtensions.cs
BizHawk.Common/Extensions/NumberExtensions.cs
BizHawk.Common/HawkFile.cs
BizHawk.Common/InstanceDll.cs
BizHawk.Common/NDBDatabase.cs
BizHawk.Common/Serializer.cs
BizHawk.Common/SettingsUtil.cs
BizHawk.Common/TempFileManager.cs
BizHawk.Common/Util.cs
BizHawk.Common/Win32Hacks.cs

See #1515, excludes `Sprintf.cs` as it's unused and should be deleted.

Use string interpolation in BizHawk.Common

---

Bizware/BizHawk.Bizware.BizwareGL.OpenTK/IGL_TK.cs
Bizware/BizHawk.Bizware.BizwareGL.SlimDX/IGL_SlimDX9.cs
Bizware/BizHawk.Bizware.BizwareGL/CGC.cs
Bizware/BizHawk.Bizware.BizwareGL/RenderTarget.cs
Bizware/BizHawk.Bizware.BizwareGL/RetroShader.cs
Bizware/BizHawk.Bizware.BizwareGL/Texture2d.cs

Use string interpolation in BizHawk.Bizware

---

BizHawk.Client.EmuHawk/tools/ToolManager.cs

Reverts TASVideos/BizHawk#1569
Check #1572.

Revert "Rewrite ToolManager.IsAvailable"

---

BizHawk.Client.EmuHawk/Program.cs
BizHawk.Client.EmuHawk/tools/ToolManager.cs

zeromus mentioned it should be lazy and also that it should use reflection-only loading, so I did it. *May* help debug #1558.
Déjà vu? #1569 was merged without being tested. We have WIP PRs now, but I've tested this one.

IsAvailable rewrite redux

---

BizHawk.Client.EmuHawk/ArgParser.cs
BizHawk.Client.EmuHawk/MainForm.cs

Adding the ability to just type `bizhawk.exe --version` to get the the version and exit. That's it!

Allow getting the version from the command line

---

BizHawk.Client.EmuHawk/Api/ApiManager.cs

Without these, External Tools can't see most of the APIs
This fixes https://github.com/TASVideos/BizHawk/issues/1752

ApiManager should add APIs from Common

---

BizHawk.Client.EmuHawk/config/GB/CGBColorChooserForm.Designer.cs
BizHawk.Client.EmuHawk/config/GB/CGBColorChooserForm.cs
BizHawk.Emulation.Cores/Consoles/Nintendo/Gameboy/GBColors.cs

Makes the libretro GBC shader an option instead of forcing Gambatte colors.

Undo Previous PR on Gambatte Colors and Implement an Option

---

src/BizHawk.BizInvoke/BizExvoker.cs
src/BizHawk.Client.Common/config/Config.cs
src/BizHawk.Client.EmuHawk/Input/GamePad360.cs
src/BizHawk.Client.EmuHawk/Program.cs
src/BizHawk.Common/IImportResolver.cs
src/BizHawk.Common/OSTailoredCode.cs
src/BizHawk.Emulation.Cores/Consoles/Nintendo/N64/NativeApi/mupen64plusVideoApi.cs
src/BizHawk.Emulation.Cores/Waterbox/PeRunner.cs
src/BizHawk.Emulation.Cores/Waterbox/PeWrapper.cs
src/BizHawk.Emulation.DiscSystem/API_MednaDisc.cs

Use IntPtr.Zero instead of (IntPtr?) null

---

src/BizHawk.Emulation.Common/Database/FirmwareDatabase.cs

Rename All the Firmware Files to have a more Unified Naming Convention

Firmware Rename

---

src/BizHawk.Client.EmuHawk/tools/TAStudio/FramesPrompt.Designer.cs
src/BizHawk.Client.EmuHawk/tools/TAStudio/FramesPrompt.cs
src/BizHawk.Client.EmuHawk/tools/TAStudio/TAStudio.Designer.cs
src/BizHawk.Client.EmuHawk/tools/TAStudio/TAStudio.MenuItems.cs
src/BizHawk.Client.EmuHawk/tools/TAStudio/TAStudio.cs

This works pretty nicely.
Notes:
- Might want to consider renaming FramesPrompt to something more generic like IntPrompt as I'm using it to get a number for something else
- Haven't done the keyboard shortcut because I don't know how, might do it tomorrow night if I get chance

clone x times

---

src/BizHawk.Client.EmuHawk/tools/TAStudio/TAStudio.cs

TAStudio: properly resume playback after painting.

---

src/BizHawk.Client.Common/movie/MovieSession.cs
src/BizHawk.Client.Common/movie/bk2/Bk2Movie.IO.cs
src/BizHawk.Client.Common/movie/interfaces/IMovie.cs
src/BizHawk.Client.EmuHawk/DisplayManager/OSDManager.cs
src/BizHawk.Client.EmuHawk/tools/TAStudio/TAStudio.cs

TAStudio: improve saving behavior

---

README.md

TODO post-merge:
* push Manjaro build script to AUR
TODO for later:
* issue template for feature requests
* homogenise code style in auto-generated Lua API docs
* update build script for NixOS
* create build script for Mint

(pre-prepared updates to documentation)

---

src/BizHawk.Client.Common/config/Binding.cs

Remove default joypad bindings for fast-forward/rewind

---

src/BizHawk.Client.EmuHawk/tools/TAStudio/TAStudio.Navigation.cs
src/BizHawk.Client.EmuHawk/tools/TAStudio/TAStudio.cs

Fix new bugs from painting during auto-restore

---

src/BizHawk.Client.EmuHawk/MainForm.FileLoader.cs
src/BizHawk.Client.EmuHawk/tools/TAStudio/TAStudio.IToolForm.cs
src/BizHawk.Client.EmuHawk/tools/TAStudio/TAStudio.MenuItems.cs
src/BizHawk.Client.EmuHawk/tools/TAStudio/TAStudio.cs

Broaden usage of TAStudio-specific movie-loading.

---

src/BizHawk.Client.Common/RomLoader.cs

Re-add M3U capability

---

src/BizHawk.Client.Common/Api/Classes/JoypadApi.cs
src/BizHawk.Client.Common/Api/Interfaces/IJoypadApi.cs
src/BizHawk.Client.Common/lua/CommonLibs/JoypadLuaLibrary.cs

It seems we didn't have a way for Lua scripts to get the inputs created by movies.

add a Lua method to get inputs from the movie

---

src/BizHawk.Client.EmuHawk/tools/GB/GBGPUView.cs
src/BizHawk.Common/IsExternalInit.cs
src/BizHawk.Emulation.Cores/Consoles/Nintendo/GBHawk/GBC_GB_PPU.cs
src/BizHawk.Emulation.Cores/Consoles/Nintendo/GBHawk/GBC_PPU.cs
src/BizHawk.Emulation.Cores/Consoles/Nintendo/GBHawk/GBHawk.IEmulator.cs
src/BizHawk.Emulation.Cores/Consoles/Nintendo/GBHawk/GBHawk.cs
src/BizHawk.Emulation.Cores/Consoles/Nintendo/GBHawk/GB_PPU.cs
src/BizHawk.Emulation.Cores/Consoles/Nintendo/Gameboy/Gambatte.IEmulator.cs
src/BizHawk.Emulation.Cores/Consoles/Nintendo/Gameboy/Gambatte.cs
src/BizHawk.Emulation.Cores/Consoles/Nintendo/Gameboy/IGameboyCommon.cs
src/BizHawk.Emulation.Cores/Consoles/Nintendo/Gameboy/Sameboy.cs

All cores can easily implement it now with no copying or awkward garbage
Fixes #2564

Rework GB GPU memory areas API

---

src/BizHawk.Client.Common/movie/tasproj/StateDictionary.cs
src/BizHawk.Client.Common/movie/tasproj/ZwinderStateManager.cs
src/BizHawk.Client.Common/movie/tasproj/ZwinderStateManagerSettings.cs
src/BizHawk.Client.Common/rewind/ZwinderBuffer.cs
src/BizHawk.Tests/Client.Common/Movie/ZwinderStateManagerTests.cs

A re-work of #2533, following #2536.
In addition, saving/loading now works properly with the new settings.

Drive states2

---

src/BizHawk.Client.EmuHawk/CustomControls/InputRoll/InputRoll.cs
src/BizHawk.Client.EmuHawk/tools/TAStudio/BookmarksBranchesBox.Designer.cs

A couple of fixes. I have not tested this outside of TAStudio, though I see no reason it would break anything.
See commit messages for details.

Input roll scrolling

---

src/BizHawk.Client.Common/movie/import/LsmvImport.cs

This is the same library and coding style we use daily to load every single savestate and movie, so it can't be that bad

Use SharpZipLib for lsmv import instead of hawkfile

---

src/BizHawk.Client.Common/BizHawk.Client.Common.csproj
src/BizHawk.Client.Common/RomLoader.cs
src/BizHawk.Client.Common/movie/import/LsmvImport.cs
src/BizHawk.Client.Common/savestates/ZipStateLoader.cs
src/BizHawk.Client.EmuHawk/AVOut/JMDWriter.cs
src/BizHawk.Client.EmuHawk/BizHawk.Client.EmuHawk.csproj
src/BizHawk.Client.EmuHawk/packages.config
src/BizHawk.Client.EmuHawk/tools/NES/NESMusicRipper.cs
src/BizHawk.Client.EmuHawk/tools/PCE/PCESoundDebugger.cs

Since .NET 4.5, there's been a good framework alternative, and it gets lots of eyes on it.  I've heard that it's quite fast in .NET Core too.

Remove icsharp

---

src/BizHawk.Emulation.Cores/Consoles/Nintendo/N64/N64SyncSettings.GLideN64.cs

Fix copy-paste description.

---

src/BizHawk.Client.DiscoHawk/MainDiscoForm.cs
src/BizHawk.Emulation.DiscSystem/DiscoHawkLogic/DiscoHawkLogic.cs

Implement missing part of DiscoHawk CLI

---

src/BizHawk.Common/BizDateTimeConverter.cs
src/BizHawk.Emulation.Cores/Consoles/Nintendo/GBA/MGBAHawk.ISettable.cs
src/BizHawk.Emulation.Cores/Consoles/Nintendo/NDS/MelonDS.ISettable.cs
src/BizHawk.Emulation.Cores/Consoles/WonderSwan/WonderSwan.ISettable.cs

Somewhat hacky, fixes #2796, the issue stems from the default DateTimeConverter, so I just hacked in a new one which overrides the bad behavior described in that issue.

fix date time display

---

Assets/EmuHawkMono.sh

For [Artix Linux](https://artixlinux.org/)

Add Artix to wrapper script

---

src/BizHawk.Client.EmuHawk/tools/TAStudio/TAStudio.IToolForm.cs
src/BizHawk.Client.EmuHawk/tools/TAStudio/TAStudio.cs

Fix weird edge case putting TAStudio in an unusual state

---

src/BizHawk.Client.DiscoHawk/MainDiscoForm.cs
src/BizHawk.Client.DiscoHawk/Program.cs
src/BizHawk.Emulation.DiscSystem/DiscoHawkLogic/AudioExtractor.cs
src/BizHawk.Emulation.DiscSystem/DiscoHawkLogic/DiscoHawkLogic.cs

Intended to fix #2953
This adds a CLI to extract MP3s.
Just use
`./DiscoHawk.exe MUSIC ./myfile.ccd OVERWRITE`

Discohawk CLI for music extraction

---

src/BizHawk.Client.EmuHawk/tools/TAStudio/TAStudio.IToolForm.cs
src/BizHawk.Client.EmuHawk/tools/TAStudio/TAStudio.ListView.cs
src/BizHawk.Client.EmuHawk/tools/TAStudio/TAStudio.cs

Commit 319455c reverted one of my previous commits, commenting that it caused a regression.
These commits redo my commit, along with fixing the regression and a very similar bug.
Morilli, you said that you would work on "a different fix". Have you begun this yet?

TAStudio update self

---

src/BizHawk.Common/FFmpegService.cs

Fixes deadlocks, and removes confusing custom parser.

Interleave output and error async in Discohawk

---

src/BizHawk.Client.Common/movie/MovieSession.cs
src/BizHawk.Client.Common/movie/interfaces/IMovieSession.cs
src/BizHawk.Client.EmuHawk/tools/TAStudio/TAStudio.cs

Alternative to #3418, fixes #3417.

Fix #3417 and improve handling of default.tasproj

---

src/BizHawk.Emulation.Cores/Arcades/MAME/MAME.cs

Workaround crashes in MAME's zlib decompression code

---

src/BizHawk.Client.Common/movie/HeaderKeys.cs
src/BizHawk.Client.Common/movie/import/FcmImport.cs
src/BizHawk.Client.Common/movie/import/Fm2Import.cs
src/BizHawk.Client.Common/movie/import/IMovieImport.cs
src/BizHawk.Client.Common/movie/import/LsmvImport.cs
src/BizHawk.Client.Common/movie/import/MmvImport.cs
src/BizHawk.Client.Common/movie/import/MovieImport.cs
src/BizHawk.Client.Common/movie/import/SmvImport.cs
src/BizHawk.Client.EmuHawk/MainForm.Movie.cs
src/BizHawk.Client.EmuHawk/MainForm.cs

Allow migrating non-SHA1 hashes on movie import

---

Common.props
Directory.Packages.props
ExternalProjects/AnalyzersCommon.props
ExternalProjects/FlatBuffers.GenOutput/FlatBuffers.GenOutput.csproj
ExternalProjects/PcxFileTypePlugin.HawkQuantizer/PcxFileTypePlugin.HawkQuantizer.csproj
ExternalToolProjects/DATParser/DATParser.csproj
ExternalToolProjects/DBMan/DBMan.csproj
ExternalToolProjects/NET48ExternalToolForm.targets
src/BizHawk.BizInvoke/BizHawk.BizInvoke.csproj
src/BizHawk.Bizware.Audio/BizHawk.Bizware.Audio.csproj
src/BizHawk.Bizware.BizwareGL/BizHawk.Bizware.BizwareGL.csproj
src/BizHawk.Bizware.Graphics/BizHawk.Bizware.Graphics.csproj
src/BizHawk.Bizware.Input/BizHawk.Bizware.Input.csproj
src/BizHawk.Client.Common/BizHawk.Client.Common.csproj
src/BizHawk.Client.EmuHawk/BizHawk.Client.EmuHawk.csproj
src/BizHawk.Common/BizHawk.Common.csproj
src/BizHawk.Emulation.Common/BizHawk.Emulation.Common.csproj
src/BizHawk.Emulation.Cores/BizHawk.Emulation.Cores.csproj
src/BizHawk.Tests.Testroms.GB.GambatteSuite/BizHawk.Tests.Testroms.GB.GambatteSuite.csproj
src/BizHawk.Tests.Testroms.GB/BizHawk.Tests.Testroms.GB.csproj
src/BizHawk.Tests/BizHawk.Tests.csproj

[docs](https://docs.microsoft.com/en-gb/nuget/consume-packages/Central-Package-Management)
This feature is supported in VS2022 from 17.2 and in the SDK from 6.0.300. ~~@zeromus plz check~~ This PR is finished, just waiting for everyone to have a compatible dev environment before merging.

Use NuGet central package management

---

waterbox/common.mak

Use fastest compression when compiling Waterbox cores in debug config

---

src/BizHawk.Client.EmuHawk/config/RewindConfig.Designer.cs

"Cofiguration" -> "Configuration"

Correct rewind dialog typo

---

src/BizHawk.Client.Common/config/MovieConfig.cs

Change OnMovieEnd default to 'Pause' instead of 'Finish'

---

src/BizHawk.Client.Common/movie/BasicMovieInfo.cs

movies: normalize loaded hashes to upper case

---

src/BizHawk.Client.Common/movie/MovieSession.cs

-closes #2292.
This does change some behavior, but hopefully the new structure is more logical and more correct. Calling `HandleFrameAfter` from `HandleFrameBefore` definitely didn't feel proper.
This is in preparation for #3989, as this changed logic should be much clearer in what specific changes TAStudio wants: If the current playback is at the end of the movie,
1. the `HandlePlaybackEnd` function should not be called and instead the movie should just stay in the mode it was previously in
2. on frame advance, input should still be recorded, even in playback mode.
The 2. point is the biggest question mark to me still. There is this line `MovieController.SetFromSticky(StickySource);` which can currently only be hit on the very first frame or when enabling recording mode, advancing to the …

Cleanup before/after frame logic in MovieSession

---

src/BizHawk.Client.Common/RomLoader.cs
src/BizHawk.Emulation.Cores/Libretro/Libretro.cs

@CasualPokePlayer Is there a way to pull a name from the core, or is this the best method?

Libretro game name
